github: DandelionSprout
custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=imreeil42@gmail.com&lc=US&item_name=Donations+to+me+(Donasjoner+til+meg)&no_note=0&cn=&currency_code=NOK&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted"]
