name: (English) Problem report form
description: To report broken websites, lists, and/or functions
labels: Problem report
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)
      description: This includes the website it happened on (if applicable), and an example page URL from that site.
      placeholder: Write the problem here.
    validations:
      required: true
  - type: textarea
    id: what-happened-screenshots
    attributes:
      label: Add screenshots below if needed
      placeholder: Paste screenshots here.
    validations:
      required: false
  - type: textarea
    id: log-photo
    attributes:
      label: Add a screenshot of the extension's logger
      description: If you're using uBlock Origin, it's recommended to filter the selection down to Blocked+Allowed+Modified, to reduce the amount of (mostly irrelevant) white-coloured log entries.<br><br>If you're using AdGuard Browser Extension, it's recommended to open "≡ Open filtering log" → use Ctrl+click to select Allowed+Blocked+Modified.<br><br>AdGuard's software apps' logs are less detailed, due to their failure to list the exact applied hiding entries:<br>   • "Adguard for Windows"' logger has a rudimentary log is at Settings → Ad Blocker → Filtering Log → ||| → Allowed+Modified+Blocked.<br>   • "AdGuard for Android"'s logger has a rudimentary log at the pie icon on the bottom bar → Recent activity → ⋮ → Uncheck "Regular" → < <br><br>If you're using Adblock Plus, the log is at F12 (The keyboard key) → Adblock Plus (The tab to the right of "Security") → Reload the page once with "Show blocked" and take a screenshot → Reload the page again with "Show allowlisted" and take a screenshot.
      placeholder: Write the problem here.
    validations:
      required: false
  - type: dropdown
    id: adblockers
    attributes:
      label: Which adblocker(s) did you use when testing this?
      multiple: true
      options:
        - uBlock Origin
        - AdGuard (Paid desktop/Android versions - Standard filtering only)
        - AdGuard (Paid desktop/Android versions - Standard filtering + DNS Blocking™™©)
        - AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
        - AdGuard Home
        - Adguard DNS
        - Adblock Plus (Firefox or Manifest V2)
        - AdBlock (Firefox or Manifest V2)
        - Blokada
        - I Still Don't Care About Cookies (The extension)
        - AdNauseam
        - Brave's built-in adblocker (a.k.a. Brave Shield)
        - Firefox's built-in tracking protection
        - Vivaldi's built-in adblocker
        - Opera's built-in adblocker
        - MS Edge's built-in tracking protection
        - DNS adblocking server(s), incl. AdGuard Public DNS and Quad9
        - Pi-hole (Support may be limited)
        - dnsmasq (Support may be limited)
        - pfBlockerNG (Support may be limited)
        - NextDNS (Support may be limited)
        - Adblocker Ultimate (Not recommended, as it's a ripoff of AdGuard's browser versions)
        - <i>(Other)</i>
    validations:
      required: true
  - type: textarea
    id: adblockers-version
    attributes:
      label: Adblocker version(s)
      placeholder: Write the version number(s), and "Other" adblockers here. Manifest V3 adblockers are not allowed here.
    validations:
      required: false
  - type: textarea
    id: which-filterlists-did-you-use-screenshot
    attributes:
      label: Which filterlists did you use? Failing to tell this with at least 10 letters or 1 image, will close the report until it has been told.
      placeholder: Paste an image, textlist, or (if nothing else is possible) uBO's "Troubleshooting Information" textbox here. This includes DNS adblocking servers.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser(s) did you use when testing this?
      multiple: true
      options:
        - Google Chrome (Manifest V2)
        - Firefox (incl. LibreFox)
        - Vivaldi
        - Brave Browser
        - Tor Browser (incl. Firefox ESR 115, Waterfox, and SeaMonkey)
        - Chromium for Linux (Manifest V2)
        - Microsoft Edge (Manifest V2)
        - Ungoogled Chromium (Manifest V2)
        - Midori Electron (not WebKit)
        - Opera (any variety)
        - Kiwi Browser
        - Waterfox Classic
        - Internet Explorer 11 (Support may be limited)
        - It's about a phone app, TV app, or console
        - <i>(Other)</i>
    validations:
      required: true
  - type: textarea
    id: browsers-version
    attributes:
      label: Browser version(s)
      placeholder: Write the version number(s), "Other" browsers, app names, or etc. here, e.g. "92.0.1234.123", "x64", "Canary", "Nightly", "no.finn.android", etc. *Very* old browser versions could be rejected; for Firefox and Chrome, the treshold was v75.0 as of October 2023.
    validations:
      required: false
  - type: dropdown
    id: oses
    attributes:
      label: Which OS(s) did you use when testing this?
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - macOS
        - Linux
        - Windows 8.1
        - Windows 7
        - Android
        - iOS (Support may be limited)
        - FreeBSD (Support may be limited)
        - OpenBSD (Support may be limited)
        - Smart-TV (Write the TV model below)
        - Game console (Write the console type below)
        - <i>(Other)</i>
    validations:
      required: true
  - type: textarea
    id: oses-version
    attributes:
      label: OS version(s)
      placeholder: Write the version number(s) and "Other" OSs here, for example "21H1", "10.14", "7.1.1", "Tizen OS", "ARM64", "Fedora 39", etc.
    validations:
      required: false
