{+block}
# Version: 05October2019v3-Alpha
# Version: 051020193 (for Adblock Plus' issue report system)
# Title: 🏔️ Dandelion Sprouts nordiske filtre for ryddigere nettsider (for Privoxy)
# Translated title: Dandelion Sprout's Nordic filters for tidier websites (for Privoxy)
# Expires: 12 hours
# Redirect: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt
# Lisens / Licence: https://github.com/DandelionSprout/adfilt/blob/master/LICENSE.md
# 🇳🇴: Denne listen dekker nettsteder for Norge, Danmark, Island, Færøyene, Grønland, og samebefolkningen. For mere informasjon, detaljer, hjelpemidler, og andre lister jeg har laget, gå til https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#norsk
# 🇩🇰: Denne liste dækker websider for Danmark, Norge, Island, Færøerne, Grønland, og den samiske befolkning. For mere information-, detaljer-, nyttige værktøjer- og andre lister, jeg har lavet, besøg https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md
# Description: 🇬🇧: This list covers websites for Norway, Denmark, Iceland, Danish territories, and the Sami indigenous population. For more information, details, helpful tools, and other lists that I've made, visit https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#english
# If you wish to remove cookie banners from Nordic websites, check out https://www.i-dont-care-about-cookies.eu/
#
# 🇳🇴: Ukategoriserte oppføringer
# 🇩🇰: Ukategoriserede regler
{+block{Uncategorised entries}}
#
# 🇳🇴: ——— Reklamer ———
# 🇩🇰: ——— Reklamer ———
{+block{——— Ads ———}}
contentMarketing
-bazaar-
.dk/ad/
.dk/ads/
.is/ad/
.is/ads/
.is/augl/
.is/skrar/augl/
.no/ad/
.no/ads/
/*-annonse-*
/_bm/abd
/annonse/*
/auglysing/*
/Bannere/*
/bazaar/*
/bilder/erotikk1.jpg
/entag.js
/js/smartbanner/*
/linktag2.js
/liveodds-button_nordicbet
/nordicbet_logo
/partners/*_ad_icon
/reklam/*
/reklame/*
/resources/dfp/*
.acdn.adnxs.com/ast/ast.js
.acdn.adnxs.com/ast/ast.js
.ad.*.no
.ad.no.doubleclick.net
.ad1.*.dk
.ad1.*.no
.adcache.*.no
.adext.inkclub.com
.ads.*.dk
.ads.*.no
.ads.no
.adserver.*.dk
.adservicemedia.dk
.akamai.net
.akamaihd.net/video-assets/
.amino.dk/images/partners/agera/240x140-forside-hardcoded*.jpg
.annonser.*.no
.austevollforlag.no/wp-content/*/annonsar/
.austevollforlag.no/wp-content/*/yachtmarine2014.
.avod-fw-config.mtg-api.com
.banner.*.no
.banner.landbrugsavisen.dk/reklame.aspx
.bannere.oslonett.no
.boligkanalen-maestro-new.azurewebsites.net
.bornholm.nu/nonsec/banner
.brandstudio.inventory.schibsted.io
.cdn.ravenjs.com
.client-stream-events.mtg-api.com
.cluster.chart.dk
.cmt.no
.damoh.vgtv.no/hic_qos
.delivered-by-madington.com
.dotbanner.dk
.dust2.dk/img/banners/*
.easy-ad.no
.emerio.no
.euroads.dk
.euroads.no
.eyjar.net/skrar/ads
.freewheel-mtgx-tv.akamaized.net
.getsentry.com
.gratisxxx.no
.helios.*.no
.i1media.no
.isweb.no
.klikk.no/common/js/klikk.desktop-thirdparty.min.js
.matriell.dm-storage.no
.media.sonymusic.no/marketing/*.html
.myad.no
.nettklikk.no
.norskenettsider.no/images/ageras-banner.jpg
.norskenettsider.no/images/remember-banner-2016.jpg
.nvnytt.no/images/*annonse-
.openadex.dk
.piwik.onlinemagasinet.no
.primetime.ad.primetime.net
.rig.idg.no
.sannsyn.com
.sentry-cdn.com
.soda.is
.ssl.p.jwpcdn.com*/freewheel.js
.ssl.p.jwpcdn.com*/jwpsrv.js
.ssl.p.jwpcdn.com*/sharing.js
.ssl.p.jwpcdn.com*/vast.js
.svonm.com/hd-main.js
.track.adform.net
.track.adform.net/Banners/
.tracking-genesisaffiliates.com
.tvshop.com/tradedoubler_files/
.vevlysingar.fo
.viafree.*/collect
.viasport-assets.mtg-api.com/*/prod/comScore-*.js
.vikari.is/skjol/frjalsi-lif*.png
.webclick.no
.webhotell.enivest.no
.feltet.dk/octo_cms/files/Feltet.dk//
.langrenn.com/getbanner.php/*/getfile.php/
/annonse_
# — — — — —
#
.adnxs.com
#
# framtia.no, sovesten.no, arendalstidende.no, bil24.no, 730.no, frettatiminn.is, opp.no
# The ':not' exception is needed for opp.no
# https://www.totensblad.no/2019/nyheter/forsynte-seg-gradig-av-medaljene-i-nm/
# https://www.op.no/
# https://arendalstidende.no/
# https://www.langrenn.com/cppage.6250314-1743.html
#
# 🇳🇴: ——— Tomme restebokser som EasyList har etterlatt ———
# 🇩🇰: ——— Tomme restebokser, som EasyList har efterladt ———
{+block{——— Leftover empty spaces that EasyList have left behind ———}}
.730.no/banner/*/sonymusic/
.bilnorge.no/gifs/*emty.gif
.gaysir.no/rek/bb_inline
.static.vg.no/css/admark_top.gif
# — — — — —
#
#
# https://sol.no/
# http://www.qxl.no/
# https://www.vtb.no/
# https://vafo.dk/
# https://reelligestilling.dk/
# https://www.rbnett.no/
# https://www.op.no/
# https://journalisten.dk/
# http://www.altomfotball.no/
# dv.is
# dinside.no, seher.no
# bt.no
# https://www.latterkula.no/se-streamerne-som-vinner-store-gevinster-mens-de-streamer-live/
# https://www.latterkula.no/artikler/
# https://www.mbl.is/frettir/
# https://adressa.no
#
# 🇳🇴: ——— Tomme skillebokser ———
# 🇩🇰: ——— Tomme adskillerbokser ———
{+block{——— Empty divider spaces ———}}
#
# 🇳🇴: ——— Distraherende bakgrunnsbilder ———
# 🇩🇰: ——— Distraherende baggrundsbilleder ———
{+block{——— Distracting background images ———}}
.images.media.xxlsports.com/images/h90/h9d/9339713159198/bg.jpg
.platekompaniet.no/assets/img/background.png
.pepcall.no/wp-content/uploads/2015/04/bakgrunn-forside.jpg
.tv2.no/s/lab/2.5/p/img/tv2-background.svg
#
# 🇳🇴: ——— Fiksing av knekte sider ———
# 🇩🇰: ——— Fiksing af knækte websider ———
{+block{——— Unbreakage ———}}
# 🇳🇴: Fikser videoavspillerene på nettstedene til norske fotballklubber når man bruker «uBlock Filters - Unbreak»
{+block{Fixes video players on Norwegian football club sites when using "uBlock Filters - Unbreak"}}
# 🇩🇰: Gør det muligt igen at scrolle når «I Don't Care About Cookies» er benyttet
{+block{Re-enables scrolling when using "I Don't Care About Cookies"}}
.scripts.tv2a.dk/oil/
{+block{Unbreaks significant content breakage when using "Fanboy's Social Blocking List", if I recall correctly}}
# Attempting to fix a problem with voting online on Idol Norway when using EasyPrivacy
# Attempts to resolve how some frontpage articles are hard to open when using EasyPrivacy.
# https://github.com/easylist/easylist/issues/1861
# 🇳🇴: Solcellespesialisten, innlastingsproblem
{+block{Solcellespesialisten, loading issue}}
.wo.tc
#
# 🇳🇴/🇩🇰: ——— Anti-anti-reklameblokkering ———
{+block{——— Anti-anti-adblocking, in the event that https://forums.lanik.us/viewtopic.php?f=23&t=42273 were to specifically mention such entries as a reason to be denied EasyList affiliation or native ABP inclusion ———}}
.dni-adops-proxy-prod-adopsmediaconverter.mercury.dnitv.com/
.elderlyscissors.com
.imasdk.googleapis.com/pal/sdkloader/pal.js
.vg.no/cnp-assets/src/sites/vg/components/AdblockModal
#
#
#
# 🇳🇴: ——— Vindusviskere for betalte artikler (sånn at de nederste linjene i en forhåndsvisning ikke toner ut) ———
# Takk til THEtomaso (https://github.com/THEtomaso) for de fleste av disse oppføringene.
# 🇩🇰: ——— Vinduesviskere for betalte artikler (så de sidste par linjer i en forhåndsvisning ikke falder ud) ———
# Tak til THEtomaso (https://github.com/THEtomaso) for de fleste af disse regler.
{+block{——— De-blurrers for paid articles (so that the last few lines of a preview doesn't fade out) ———}}
# Thanks to THEtomaso (https://github.com/THEtomaso) for most of these entries.
.dagligvarehandelen.no/sites/all/themes/custom/ledelseas/gfx/veil.png
#
# 🇳🇴: ——— Norsk Tipping, inkl. tvilsomt motiverte lottoreklamer (Noen ikke-påtrengende tippereklamer er greit nok i mine øyne) ———
# 🇩🇰: ——— Norsk Tipping, inkl. nogle tvivlsomt motiverede lottoreklamer (Nogle ikke-påtrængende sportstipsreklamer er akseptabelt i mine øjne) ———
{+block{——— Norsk Tipping, incl. poorly motivated lotto ads (A few non-pushy football pool ads are fine in my book) ———}}
.widget.norsktippingpartner.no
.widget.tippebannere.no
.tipster.no/embed
#
# ——— Gamereactor ———
# 🇳🇴: Disse oppføringene synkroniseres med de til «Frellwit's Swedish Filter» med noen måneders mellomrom, så det hadde blitt for strevsomt å kategorisere dem.
# 🇩🇰: Disse regler bliver synkroniseret med de hos «Frellwit's Swedish Filter» med nogle måneders mellemrum, så det hadde blivet for tungt at kategorisere dem.
{+block{These entries are synchronised with those of "Frellwit's Swedish Filter" every few months-ish, and as such it'd be too much work to categorise them.}}
.gamereactor.*/lay/ad-video-stats.
.gamereactor.*/lay/js/adblock_desktop.
.gamereactor.*/lay/js/background.
.gamereactor.*/lay/js/banners_config.
.openx.gamereactor.dk/multi.php?
.gamereactor.*/media/eventad/
.media.gamereactor.dk/prerolls/*
.ssl.p.jwpcdn.com*/gapro.js
/insert_grtv_stats.
/prerolls/*
/adblock_mobile.
/viewability.
#
# 🇳🇴: Korrigerer veldig grell feilinformasjon på Elkjøp og Elgiganten Danmark, hvor EU-energimerkingen til en del produkter fortsatt brukte før-2016-fargene, som førte til tilfeller hvor f.eks. en A-merking var mørkegrønn mens en A+-merking var gul med et hint av grønt.
# 🇩🇰: Rætter op i rigtigt grim fejlinformation på Elgiganten og Elkjøp, der EU-energimærkingen til mange produkter stadigt benytter før-2016-fargene, noget der førede til tilfelder der fx. et A-merke var mørkegrøn mens et A+-merke var gult med et hint af grøn.
{+block{Fixing very severe misadvertising on Elkjøp and Elgiganten Denmark, in which the EU energy labels for a lot of products were still showing the colours of the pre-2016 labels, leading to cases where e.g. an A label was dark green while an A+ label was yellow with a hint of green.}}
# Amazingly, this does not seem to be a problem on elko.is or elding.fo, so kudos to them.
#
# ——————————————————————————————————————————————————————————————————————————————————————————————————————
#
# 🇳🇴: Nettsteder jeg nekter å besøke selv for å førstehåndsteste oppføringene
{+block{Sites that I refuse to visit on my own to test the entries}}
#
# ——————————————————————————————————————————————————————————————————————————————————————————————————————
#
{+block{Category: Compatibility entries for ABP users, EasyList, and/or functionality whitelisting}}
#
# 🇳🇴: Hvitelisting av sporere som er nødvendige for brukere av Prisjakt, Kickback, og Viatrumf
# 🇩🇰: Tracker-hvidlistninger, der er nødvendige for brugere af Prisjagt, såvel som de norske handletjenester Kickback og Viatrumf
{+block{Tracker whitelistings that are necessary for users of Prisjakt, Kickback, and Viatrumf}}
# 🇳🇴: Lagt til fordi min egen mor (Hun er i 40-årene) trodde jeg hadde rotet til PCen hennes, når den i stedet bare viste en uBO-sideadvarsel på grunn av en oppføring i «AdGuards hovedfilter», også kjent som AdGuard Base.
{+block{Added because my own mom (She's in her 40s) thought I had messed up her PC, when instead it just displayed a uBO page warning due to an AdGuard Base entry.}}
#
# 🇳🇴: Landseksklusive versjoner for enkle reklameblokkerere, av flernasjonsoppføringer som er i utvidelsesfilen for avanserte reklameblokkerere; ettersom Adblock Plus og AdGuard for øyeblikket ikke støtter *-jokertegn i nettadressene til blokkeringsregler.
# ABP diskuterte på et tidspunkt å støtte det i https://issues.adblockplus.org/ticket/6773, men det bunnet ut i ingenting.
# 🇩🇰: Landseksklusive versioner til enkle adblockere, af flerlandsregler, der findes i udvidelsesfilen for avancerede adblockere; eftersom Adblock Plus og AdGuard i øjeblikket ikke understøtter * -jokertegn i blokeringsregel-URL-er.
# ABP drøftede på et tidspunkt at støtte det i https://issues.adblockplus.org/ticket/6773, men det førede ikke til noget.
{+block{Country-exclusive versions for simple adblockers, of multi-country entries that are found in the extensions file for advanced adblockers; because Adblock Plus and AdGuard currently doesn't support *-wildcards in blocking-rule URLs.}}
# ABP was at one point discussing supporting it in https://issues.adblockplus.org/ticket/6773, but it stranded out into nothing.
#
#
#
#
{+block{Entries that are also present in AdGuard English Filter, for those who use ABP and AdBlock, or who haven't felt a need to spend 8 seconds to subscribe to it in uBlock Origin.}}
#
#
# ——————————————————————————————————————————————————————————————————————————————————————————
#
# 🇳🇴: Svindelnettsteder og virusnettsteder (Ikke besøk dem hvis du har dine datamaskiner og lommebøker kjært)
# Rask leksjon: Mange svindelnettsteder bruker adresser som ligner på adressene til store nettsteder, men som inneholder tilfeldige ekstra smådetaljer som gjør dem til en helt annen adresse. ".vg.no." vil blokkere vg.no.iphone-svindel-eksempel.xyz, men ikke vg.no eller vg.no/sport
# 🇩🇰: Fupsider og virussider (Besøg dem ikke, hvis du sætter pris på dine computere og tegnebøger)
{+block{Scam sites and virus sites (Do not visit them if you value your computers and wallets)}}
# Quick 101: Many scam sites use addresses that resemble those of major sites, but which contain random extra tidbits that make them a whole different address. ".vg.no." will block vg.no.iphone-scam-example.xyz, but not vg.no or vg.no/sport
.kjolenorge.com
.paypal.*.no
.vg.no.
.elkjop.no.
.coop.no.
.shell.no.
.finn.no.
.posten.no.
.postnord.no.
.*/finn.no/finno.htm
.dnb.no.
.sparebank1.no.
.nordea.no.
.sbanken.no.
.danskebank.no.
.*/?finn.no/login
.komplett.no.
.nordnet.no.
.skatteetaten.no.
.*/begrensede-tilbudet/
.norwegian.com.
.flysas-no.
.tusenfryd-com.
.*/bli-avbrutt-bor-du-oppdater/
.*/Norgesecure/
..gratis-reisebilletter.
.*/KiwiErbjudanden1/
.trackvoluum.com
.jagerjack.com
.*/pakkerlevering/
.posten.club
.kundklubb-se.com
.prisjakt.org
.postnord-norge.com
.102.112.2o7.net
.tromselementbygg.no
.no.zxxyw.com
.digitoday.com
.apple-account-locked.losjevegen.no
.arvetellefsen.no/curry
.holmedalblikk.no
.vipps-sikkerhet.*
.*/dnb11111/
.nymelding.com
.mrcal365.com
#
# 🇳🇴: Som nevnt i diverse nyhetsartikler om svindelsider
# 🇩🇰: Som nævnt i diverse nyhedsartikler om fupwebsider
{+block{As mentioned in various news articles about fraud sites}}
# https://www.dagbladet.no/kultur/jeg-blir-hver-dag-kontaktet-av-folk-som-faktisk-tror-pa-denne-svindelen/70487841
.breakoutstory24.com
.thefivereport.online
# https://www.tv2.no/nyheter/10493336/
.rnbinance.com
.brightertrade.com
# https://www.nrk.no/ytring/1.14496024
.cost2buy.net
# https://www.nrk.no/norge/1.14511067
.kongeparken.com-*
.com-fryd.com
.kiwi.com-*
.com-norwegian.com
# https://www.aftenposten.no/osloby/i/mRK8xq/Fatt-tilbud-om-gratis-kollektivbillett-Svindel_-melder-Ruter
.ruter.top
# https://www.faktisk.no/faktasjekker/YAb/nei-olav-thon-har-ikke-investert-850-millioner-kroner-i-bitcoin-program
.101mesh.com
.gokkw.com
.earnmoneyglobal.com
# https://www.datahjelperne.no/stein-erik-hagen-og-fredrik-skavlan-misbrukes-i-bitcoin-svindel/
.trendyn.me
# https://www.datahjelperne.no/verifiser-get-konto-falsk-mail/
.getmail-no.*
# https://www.datahjelperne.no/falske-telenor-undersokelser/
.surveryrewards1.com
# https://www.nrk.no/mr/1.14649436
.pprfct.com
#
# 🇳🇴: Falske nett-"butikker" som er så dårlige, at de står oppført på Forbrukertilsynet egen svarteliste.
# 🇩🇰: Falske web-"butikker" der er så dårlige, at de er opført på svartelisten til Forbrukertilsynet (Norges svar på Forbrugerombudsmanden).
{+block{Fake and fraudulent web-"stores" that are so bad, that they're listed on the blacklist of the Norwegian state-sponsored Consumer Authority.}}
# Source: https://www.forbrukertilsynet.no/netthandel/falske-nettbutikker.
.adidasko.com
.adidassuperstarnorge.com
.airmaxskobillige.com
.allergyfl.com
.apvoc-ga.com
.ashskonorge.com
.assassinfitness.com
.benshermanoslo.com
.billigesalg.com
.billigskos.com
.bilstokken.com
.bncentertainment.com
.bostongrnhsflowers.com
.caperforaciones.com
.charpente-ramel.com
.coralls.com
.crossfiterada.com
.crownedwithlaurels.com
.daradis.com
.denningwelldrilling.com
.drakternorge.com
.drcarolyngroff.com
.dunjakke-no.com
.easyliving4you.com
.eurosko.net
.fatalfailblog.com
.festmusikk.com
.fotballsko-salg.com
.fotballskotilbud.com
.gantoslo.com
.godeskonettbutikk.com
.godsfillingstation.org
.gsport.com
.helseprodukt.co
.hernoclothing.com
.hollisternorge.com
.horizonbagel.com
.itsthetrendydealstore.com
.jakkesalgs.com
.jakkesnorge.com
.joseph-holland.com
.klmyu.com
.jessicaivory.com
.legarralazcoz.com
.lindseysopticians.com
.linkshe.com
.locchalet2alpes.com
.lrgst.com
.lymaq.com
.manasporthorse.com
.mayor4london.com
.mbtnorge.com
.meadtalkofthetown.com
.meladermfacts.com
.mncprobuild.com
.moebel-thiems.com
.moslt.com
.moteshoes.com
.mrarmstrongsclass.com
.mudancaslvc.com
.museuw.com
.mycraftypad.com
.nasajones.com
.nikebutikks.com
.no.moncleritalien.com
.nordartisan.com
.norfotball.com
.norgefotball.com
.norge.parkaoutdoor.com
.norgejakke.com
.norgejakkerbutikk.com
.norgeshoes.com
.oflike.com
.omgrm.com
.ontariokitcarbuilders.com
.parajumpers-longbear.com
.parajumpers-salg.com
.parajumpersitoutlet.com
.parajumpersit.com
.parajumperjakke.net
.parajumpersnettbutikk.com
.parajumpers-norge.site
.parajumpersnorway.com
.parajumperssalg.com
.parajumpersoutletnorge.com
.pmnft.com
.pjs.outlet.com
.popeurope.com
.quiltstudiolaren.com
.reeconindustries.com
.retoaudi.com
.scottfamilyministries.org
.skoeccosandaler.com
.skonmdnorge.com
.sykkeltrøye.com
.ssrodeolivestock.com
.swellsup.com
.tiranaaquapark-eg.com
.tobiascelebritymusicevents.com
.um-bs.com
.vansnorge.com
.wausauorthopedics.com
.zaskal.com
#
{+block{Pirate-product-selling stores registered by the serial scammers who go by the name of "xiang dao xin xi ji shu you xiang gong si".}}
.nofotballshop.com
.nofotballstore.com
.dkfodboldstore.com
