# Title: 🏔️ Dandelion Sprouts nordiske filtre for ryddigere nettsider (for Privoxy)
# Title 🇬🇧: Dandelion Sprout's Nordic filters for tidier websites (for Privoxy)
# Last modified: 14August2025v1-Deprecated
# Lisens / Licence: https://github.com/DandelionSprout/adfilt/blob/master/LICENSE.md
# Homepage: https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md
# 🇳🇴：Denne listen dekker nettsteder for Norge, Danmark, Island, Færøyene, Grønland, Schleswig-Holsteins danske minoritet, og samebefolkningen. For mere informasjon, detaljer, hjelpemidler, og andre lister jeg har laget, gå til https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#norsk
# 🇩🇰：Denne liste dækker websider for Danmark, Norge, Island, Færøerne, Grønland, Sydslesvig, og den samiske befolkning. For mere information-, detaljer-, nyttige værktøjer- og andre lister, jeg har lavet, besøg https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#dansk
# 🇳🇴🏞：Denne lista dekkar nettstader for Noreg, Danmark, Island, Færøyane, Grønland, Schleswig-Holsteins danske minoritet, og samefolkesetnadene. For meire informasjon, detaljar, hjelpemiddel, og anna listar eg har laga, gå til https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#norsk-nynorsk
# Description: 🇬🇧: This list covers websites for Norway, Denmark, Iceland, Danish territories, Schleswig-Holstein's Danish minority, and the Sami indigenous population. For more information, details, helpful tools, and other lists that I've made, visit https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#-english
# If you wish to remove cookie banners from Nordic websites, check out https://filters.adtidy.org/windows/filters/18.txt
# Starting 13 May 2024, reports about non-blocked banners on digi.no and tu.no must instead be sent to https://reports.adguard.com/new_issue.html and/or https://github.com/uBlockOrigin/uAssets/issues. No exceptions under any circumstances. They're simply far, far better at them than me. They must either fix it on their own, or have written all needed entries on their own in advance before they forward such reports to me. If they ever say otherwise, show them this line of text.
# Starting 10 April 2025, comments under so-called "commits" on GitHub will not be read under any circumstances. Other comment methods on GitHub will still be read.
# 🇳🇴：Fjerning av reklamebokser og tomme overskuddsbokser
# 🇩🇰：Fjernelse af annonceboxer og tomme overskudsrammer
# 🇬🇧：Ads and leftovers removal entries / Hiding-type rules
# — — — — — — — — — — — — — — — — — 
# 🇳🇴：Oppføringer for minst 3 nettsteder
# 🇬🇧：Entries for at least 3 websites
# — — — — — — — — — — — — 
# 🇳🇴：Brede eller heldomenebaserte blokkeringsoppføringer
# 🇬🇧：Broad or whole-domain blocking rules
.dk/ad/
.dk/ads/
.is/ad/
.is/augl/
.is/netbordar/
.is/skrar/augl/
.no/ad/
/annonsar/*
/annonse_
/auglysing/*
/auglysingar/*
.no/api/unit-image?
/vefauglysingar/*
ad1.*.dk/
ad1.*.no/
ads.*.is/
ads.*.no/
ads2.*.no/
adserver.*.dk/
auglysingar.*.is/
banner.*.no/
helios.*.no/
vefbordar.*.is/
vevlysingar.*.com/
ad.shareholders.dk/
adext.inkclub.com/
.adnordics.com/
adserver.xh.no/
.adservice.com/
.adservicemedia.dk/
advert.*.no/
advertisement.*.no/
banner.3loops.com/
.betterbanners.org/
bilborsen.webannonse.no/
boligkanalen-maestro-new.azurewebsites.net/
cluster.chart.dk/
.delivered-by-madington.com/
.dotbanner.dk/
.easy-ad.no/
.easy-ads.dk/
heartbeat.airserve.net/
images.passendo.com/
.isweb.no/
kunde.apt.no/
kynning.olis.is/
matriell.dm-storage.no/
ndstage.wpengine.com/
openad.visir.is/
samfilm.codelab.is/
.sannsyn.com/
static.airserve.net/
.tankeogteknikk.no/
.tracking-genesisaffiliates.com/
.vefbordi.is/
.vevlysingar.fo/
videotool.fbg.dk/
.svindel.info/
.pliing.com/
.admob.no/
.admob.dk/
.adpepper.dk/
banner10.zetasystem.dk/
print2web.sn.dk/
lib.idg.no/
{+block{AdressaNO}}
drbrand.herokuapp.com/
{+block{bobilverdenNO}}
/annonse-
{+block{https://www•ballade•no/}}
/wp-content/uploads/*_Annonse_
{+block{https://www.osterud.name/FF57W10/norwegian-filters.txt}}
/bannerannonser/*
{+block{byggenyttNO}}
/_annonser
{+block{frendeNO}}
{+block{https://malviknytt•no/2020/07/31/skyting-pa-hjemmebande/ (16/08/2020)}}
/Nettbanner-
{+block{sexpigerDK}}
{+block}
.lh3.googleusercontent.com/*=w468-h60-
{+block}
.lh3.googleusercontent.com/*=w970-h250-
# salangen-nyheterCOM, hytteavisenNO, strafferundenNO, langrennCOM (12/10/2020)
/getbanner.php
# biffNO (26/10/2020)
^.*_nettannonse.
/BINARY/*-BANNER-*.gif
/BINARY/*%20200x300.jpg
# nettNO (30/11/2020)
/byteads
# adressaNO (02/12/2020)
/polarnexus.js
# reavisaNO (06/12/2020)
^.*_nettbanner_
^.*_visittkortannonse_
-visittkortannonse-
# ytresognNO (16/12/2020)
/hnuannonse
# heilsutorgIS (17/04/2021)
.is/static/strevda/
# fugleognaturDK (14/05/2021)
/images/bannere
{+block{https://norges•online/produkt/nestle-viking-melk-410-g}}
.fr135.net/
.static-dscn.net/
{+block{skagensavisDK}}
/wp-content/uploads/i123_ads/*.gif
/wp-content/uploads/i123_ads/*_460x196.jpg
/wp-content/uploads/i123_ads/930x180_
{+block{tv-kalundborgDK}}
/system_files/banner/ckfinder
# keldanIS (05/01/2021)
/images/augl
{+block}
.tac.is/kunnar
# isolorNO (16/01/2021)
-skyskraper-annonse.
# norskemagasinetCOM (24/01/2021)
{+block}
.img.norrbom.com/*-300x60.png
# vgNO (14/04/2021)
/gfx/fishfingers
{+block{xpresstrykDK}}
{+block}
.images.staticjw.com/*/casino24.jpg
{+block{https://www•diabetes•no/mer/nyheter-om-diabetes/nyheter-2021/sporsmal-og-svar-om-koronavaksinen-og-diabetes/ (16/11/2021)}}
/globalassets/banner_
{+block{https://github.com/AdguardTeam/AdguardFilters/issues/114245#issuecomment-1085683154}}
.no/vendor/apx
{+block{https://viivilla•no/hage/terrasse/slik-gjor-du-terrassen-festklar-til-17-mai-pa-1-2-3/ (18/05/2023)}}
gcp.passendo.com/
.psscdn.com/
# samferdselinfraNO (18/05/2023)
/wp-content/uploads/ad-html
{+block{https://spurt•no/zyrtec-mot-myggstikk/ (01/06/2023)}}
/convertpro/*/cp-popup.min.css
{+block{https://www•version2•dk/artikel/medie-yngre-er-til-nemid-aeldre-til-mitid (02/11/2023)}}
{+block}

# vilgernelevelDK (25/12/2023)
{+block}
.skisverige.dk/*banner_*.gif
# skessuhornIS (29/12/2023)
app.pulsmedia.is/
{+block{https://bygge-anlaegsavisen•dk/historisk-vejprojekt-mellem-sisimiut-og-kangerlussuaq-undervejs (30/12/2023)}}
{+block}
.s3.eu-west-1.amazonaws.com/ads.
{+block{https://www•minmote•no/interioer/gjoer-det-selv/a/EQBava/slik-faar-du-den-perfekte-uteplassen-til-vaarsesongen}}
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-8408727}}
.tize.no/
# snDK (19/07/2024)
/annoncer/scripts/*
{+block{https://inmagasinet•custompublish•com/blir-det-gull•4528974-87197•html}}
/annonser-vert.gif
{+block{https://www•motorhobby•no/no/events/arr-etter-type/item/6-stjordal-motorshow-trondheim-mai-2025-stjordal-motorshow-i-abrahallen (13/09/2024)}}
.no/images/banners/
# nordsoepostenDK (17/02/2025)
.dk/wp-content/uploads/ap-plugin-upload
{+block{https://byggeri-arkitektur•dk/600-boliger-skal-renoveres-i-Gellerupparken-og-bliver-til-750 (20/04/2025)}}
{+block}
.cloudfront.net/mediaxpress/ad
{+block}
.cloudfront.net/mediaxpress/banner
# Borrowed from "Frellwit's Swedish Filter" (29/11/2024)
.spania.no/
plausible.webfokus.no/
.bytelab.dk/
.cncpt.dk/
gtm.findroommate.dk/
.nichehuset.dk/
.step.dk/
# — — — — —
# 🇳🇴：Domenefokuserte blokkeringsoppføringer
# 🇳🇴🏞：Domenefokuserande bloknadsoppføringar
# 🇳🇴：Domænefokuserede blokeringsindførsler
# 🇩🇰：Domain-speficic blocking-entries
{-block}
.no/api/tekjobb|
{-block}
.cdnboligkanalen.azureedge.net/*width=2000
{-block}
.musikknyheter.no/banners/skribent
{-block}
.n247.no/salg/an_%7B40
{-block}
.n247.no/salg/an_%7B6C
{-block}
.n247.no/salg/karusell_17
{-block}
.radiohallingdal.no/abanners/img/facebook.
{-block}
.siglo.is/static/strevda/*upphafssida
blob:https://www.veier24.no/
{+block}
.1819.is/infosmall/
{+block}
.730.no/banner/*/sonymusic/
{+block}
.aa-cdn.mytaste.org/js/ad.js
{+block}
.aftenposten.no/seksjon/dist/ads-
{+block}
.amino.dk/images/partners/agera/240x140-forside-hardcoded*.jpg
{+block}
.annoncelight.dk/Graphics/banner
{+block}
.appetitt.no/uploads/library/*_1150x350*.jpg
{+block}
.appetitt.no/uploads/library/*_Bannere_
{+block}
.appetitt.no/uploads/library/*_widescreen_1920x1080_*.jpg
{+block}
.appetitt.no/uploads/library/1150*
{+block}
.appetitt.no/uploads/library/320x640-*.png
{+block}
.appetitt.no/uploads/library/Annis.jpg
{+block}
.appetitt.no/uploads/library/Topp-banner-*.jpg
{+block}
.arendalstidende.no/wp-content/uploads/*_490px.jpg
{+block}
.austevollforlag.no/wp-content/*/yachtmarine2014.
{+block}
.austurfrett.is/images/*augl.jpg
{+block}
.ballade.no/wp-content/uploads/*Uke*_Sky
{+block}
.banner.landbrugsavisen.dk/reklame.aspx
{+block}
.biip.no/wp-content/uploads/*320x250.jpg
{+block}
.bilbasen.dk/Vip/GetVipFinanceBanner
{+block}
.bobilverden.no/wp-content/uploads/*/Banner-1200x300px.jpg
{+block}
.bornholm.nu/nonsec/banner
{+block}
.canariposten.no/wp-content/uploads/300x1500*
{+block}
.check-in.dk/wp-content/uploads/*_930x180.gif
{+block}
.cms.sona.fo/ads
{+block}
.danishfamilysearch.dk/images/xp2
{+block}
.deals.innocode.no/api
{+block}
.detailersclub.no/uploads/*_banner.
{+block}
.dust2.dk/img/banners/*
{+block}
.erotikmix.dk/mixads300.html
{+block}
.escort46.dk/bg_images
{+block}
.eyjar.net/skrar/ads
{+block}
.fcbarcelona.dk/*/images/footerbg.jpg
{+block}
.fcbarcelona.dk/images/bcn_*.gif
{+block}
.feltet.dk/*/topbanner_*.jpg
{+block}
.feltet.dk/*/wallpaper_1.jpg
{+block}
.feltet.dk/*_300x60.gif
{+block}
.footy.dk/wp-content/uploads/*/Sk%C3%A6rmbillede-*.png
{+block}
.forum.flyprat.no/images/r/Header
{+block}
.frilansinfo.no/wp-content/themes/frilansinfo-no/img/*-annonse.jpg
{+block}
.gamer.no/?module=Tumedia\DFProxy\Modules
{+block}
.gaysir.no/rek
{+block}
.healthtalkweb.s3.amazonaws.com/images/*_560x210.
{+block}
.hnytt.no/wp-content/uploads/*/Fluffy.jpg
{+block}
.i0.wp.com/bobilportalen.no/*/180x500.png
{+block}
.img.sofabold.dk/images/banner
{+block}
.indblik.net/wp-content/uploads/angwp
{+block}
.isolor.no/wp-content/uploads/*-toppbanner-
{+block}
.isolor.no/wp-content/uploads/*_480x150px.jpg
{+block}
.karfan.is/*-470x130*.jpg
{+block}
.karfan.is/*300x250.jpg
{+block}
.karfan.is/wp-content/uploads/*-vefbor%C3%B0i-
{+block}
.ksu247.no/wp-content/uploads/*-300x64.jpg
{+block}
.ksu247.no/wp-content/uploads/*/banner-*.jpg
{+block}
.ksu247.no/wp-content/uploads/*/BP-logo-*.png
{+block}
.ksu247.no/wp-content/uploads/*/Bunnpris2.jpg
{+block}
.leikjaland.is/*/bannerstopright/
{+block}
.leikjaland.is/images/*logo.png|
{+block}
.levmeddiabetes.no/content/uploads/*/Accu-
{+block}
.magasinetreiselyst.no/wp-content/*_annonse*promo
{+block}
.malviknytt.no/*/ani*-*.gif
{+block}
.malviknytt.no/wp-content/uploads/*-998x1024.jpeg
{+block}
.malviknytt.no/wp-content/uploads/*-firkant-*e1*.
{+block}
.mc-avisa.no/wp-content/uploads/*/Banner-*.jpg|
{+block}
.media.sonymusic.no/marketing/*.html
{+block}
.melkoghonning.no/wp-content/uploads/*_980x300px.jpg
{+block}
.melkoghonning.no/wp-content/uploads/*_Banner_
{+block}
.mmm.dk/safeframe
{+block}
.n247.no/salg
{+block}
.ni.dk/ni-img/*banner
{+block}
.nocc.no/System_Promoteringssaker
{+block}
.nordlysid.fo/lysing
{+block}
.norskenettsider.no/images/ageras-banner.jpg
{+block}
.norskenettsider.no/images/remember-banner-2016.jpg
{+block}
.nvnytt.no/images/*annonse-
{+block}
.nyteknikk.no/images.php/180x
{+block}
.nyteknikk.no/images.php/x150
{+block}
.oppdrettstorget.no/images/cms
{+block}
.oyggjatidindi.com/vev_banners/*L%C3%BDsing
{+block}
.r7.fo/lysing
{+block}
.radiohallingdal.no/abanners
{+block}
.radiorana.no/wp-content/uploads/*-300x300.jpg
{+block}
.radiorana.no/wp-content/uploads/*/Meyership.jpg
{+block}
.radiorana.no/wp-content/uploads/*/Telemix2.jpg
{+block}
.reavisa.blob.core.windows.net/*-annonse-
{+block}
.reavisa.blob.core.windows.net/*-NET.jpg
{+block}
.reavisa.blob.core.windows.net/*-NETT.jpg
{+block}
.reavisa.blob.core.windows.net/*_300x100
{+block}
.reavisa.blob.core.windows.net/*_annonse_
{+block}
.reavisa.blob.core.windows.net/*_NETT.jpg
{+block}
.reavisa.blob.core.windows.net/*visittkort
{+block}
.reiseliv.no/wp-content/uploads/*-Annons%C3%B8rinnhold-*-Aksjer-*.
{+block}
.rett24.no*/_/attachment/inline/
rett24.no*bannerizor.js/
{+block}
.ridr.dk/images/partners
{+block}
.s3-eu-west-1.amazonaws.com/froya/*-980x500-
{+block}
.s3-eu-west-1.amazonaws.com/froya/*-annonse-*.gif|
{+block}
.s3-eu-west-1.amazonaws.com/froya/*-toppannonse-
{+block}
.s3-eu-west-1.amazonaws.com/froya/*.-jpg.jpg|
{+block}
.s3-eu-west-1.amazonaws.com/froya/*.jpeg.jpg|
{+block}
.s3-eu-west-1.amazonaws.com/froya/*nettannonse-
{+block}
.s3-eu-west-1.amazonaws.com/froya/bilder/nordbohus.gif|
{+block}
.saernieh.no/wp-content/uploads/2020/03/j%C3%B8rn-jensen.jpg
{+block}
.seksualitet24.no/wp-content/uploads/*/sinful_
{+block}
.skagensavis.dk/annonceblok_baggrund.jpg
{+block}
.skagensavis.dk/wp-content/uploads/i123_ads/skagennet
{+block}
.smakmagasinet.no/contentassets/*/170x500-
{+block}
.smakmagasinet.no/contentassets/*/970x250-
{+block}
.spaniaidag.no/wp-content/uploads/*/Alltihus.jpg
{+block}
.spaniaidag.no/wp-content/uploads/*/Ceru-Design-Web-*.jpg
{+block}
.spaniaidag.no/wp-content/uploads/*/Kolstad-Gif-SI.gif
{+block}
.spanienidag.es/sites/default/files/patrocinadores
{+block}
.static.vg.no/css/admark_top.gif
{+block}
.stream.fo/wp-content/uploads/*-300x111.jpg
{+block}
.teknologiskmatforum.no/ViewImage.aspx?*width=343
{+block}
.tvsporten.dk/media/tvchannels/100x60_logo.png
{+block}
.thaiguiden.no/tg-980.html
{+block}
.thainytt.no/files/*-160.jpg
{+block}
.thainytt.no/files/160_*
{+block}
.travservice.dk/wp-content
{+block}
.trolli.is/wp-content/*/banner
{+block}
.trolli.is/wp-content/*/benecta.png
{+block}
.trolli.is/wp-content/*/Hollin_olafsfirdi
{+block}
.trolli.is/wp-content/*/syngjum-kubbur
{+block}
.trolli.is/wp-content/*/vefsmarinn
{+block}
.trolli.is/wp-content/*/videoval_logo
{+block}
.trolli.is/wp-content/uploads/*logo-*.png
{+block}
.trolli.is/wp-content/uploads/2018/05/Untitled-1-1.jpg
{+block}
.tunnelsyn1.files.wordpress.com/*/sotra-trelast-isolasjon
{+block}
.tv-kalundborg.dk/system_files/banner
{+block}
.tv2.no/prod/sponsor
{+block}
.tvkampen.com/media/*/banner*
{+block}
.tvkampen.com/media/partners/unibet-lo
{+block}
.utrop.no/wp-content/uploads/*/Banner_utrop
{+block}
.utrop.no/wp-content/uploads/2019/07/utrop.no_-1.jpg
{+block}
.utvarpsaga.is/file/*-bordi.jpg
{+block}
.utvarpsaga.is/file/*_banner.png
{+block}
.vaktin.is/grkuk
{+block}
.veitingageirinn.is/haus20g.jpg
{+block}
.verktoy24.no/wp-content/uploads/*/Banner-*px.jpg
{+block}
.verktoy24.no/wp-content/uploads/*_300px-scaled.jpg
{+block}
.vf.is/media/1/*2000x616.jpg
{+block}
.vf.is/media/1/geysir-dekkjaskipti.jpg
{+block}
.viasport-assets.mtg-api.com/*/prod/comScore-*.js
{+block}
.vikari.is/skjol/frjalsi-lif*.png
{+block}
.viralefilmer.no/wp-content/uploads/*slot-
{+block}
.webforumet.no/blogg/wp-content/uploads/AD-*.jpg
{+block}
.webforumet.no/images/*-250x250.jpg
www-presse-fotos-dk.filesusr.com/
{+block}
.xklub.dk/bannercache
{+block}
.xklub.dk/xsite/img/banner
{+block}
.xn--bredbnd-ixa.dk/wp-content/*/velkommen_banner
{+block}
.youtube.com/embed/*&origin=https%3A%2F%2Fwww.feltet.dk&widgetid=1
{+block}
.yrkesbil.no/gifs/1pix.gif
{+block}
.ytresogn.no/ete/index.html
{+block}
.ytresogn.no/wp-content/*-copy.jpg
{+block}
.ytresogn.no/wp-content/*-Topbanner-
{+block}
.ytresogn.no/wp-content/uploads/*-1.jpg
{+block}
.ytresogn.no/wp-content/uploads/*-nett.jpg
{+block}
.ytresogn.no/wp-content/uploads/2016/04/128829765_1713260288837784_946999945581640675_n.jpg
{+block}
.ytresogn.no/wp-content/uploads/2016/04/default_file-1607345037.png
{+block}
.ytresogn.no/wp-content/uploads/2016/04/Fj.-Varmepumpe.png
{+block}
.ytresogn.no/wp-content/uploads/2016/05/Fureli-nett-mobil.jpg
{+block}
.ytresogn.no/wp-content/uploads/2017/04/image007.jpg
{+block}
.ytresogn.no/wp-content/uploads/2020/02/Ytre_718_360_2.jpg
{+block}
.gamereactor.*/ads
{+block}
.gamereactor.*/exclusive.json
{+block}
.datamaskin.biz/ad/
{+block}
.ukenr.no/bobs/iframe.php
{+block}
.ugenr.dk/bobs/iframe.php
{+block}
.cdplanet.no/images/previews/*_app_preview.png
{+block}
.infohelgeland.no/banner
{+block}
.fotballen.eu/*468*.gif
{+block}
.fotballen.eu/20*/bet
{+block}
.fotballen.eu/20*/chips.jpg|
{+block}
.fotballen.eu/20*/folkeriket.jpg|
{+block}
.fotballen.eu/20*/html/images/jack.jpg
{+block}
.fotballen.eu/20*/vaiplay
{+block}
.fotballen.eu/20*casino.
{+block}
.sportsidioten.no/wp-content/uploads/*-oslo-sportslager-pc.
{+block}
.counter4all.dk/wp-content/uploads/*-300x250.
{+block}
.kjavis.dk/wp-content/uploads/20*/900x180_
{+block}
.kjavis.dk/wp-content/uploads/20*-Banner-
{+block}
.kjavis.dk/wp-content/uploads/20*/Ann-
{+block}
.kjavis.dk/wp-content/uploads/20*/jme3.png
{+block}
.kjavis.dk/wp-content/uploads/20*_300x250px_
{+block}
.kjavis.dk/wp-content/uploads/20*/Vaffelhuset-1.png
{+block}
.kjavis.dk/wp-content/uploads/20*/Ryobi-Slag-JPEG.
{+block}
.kjavis.dk/wp-content/uploads/20*/berghodt.jpg
{+block}
.kjavis.dk/wp-content/uploads/20*_ann_
{+block}
.kjavis.dk/wp-content/uploads/20*/annonce-
{+block}
.kjavis.dk/wp-content/uploads/20*/Marslev-cykler-1.png
{+block}
.kjavis.dk/wp-content/uploads/20*/Kirkeladen.png
{+block}
.kjavis.dk/wp-content/uploads/20*/Aeldresagen-1-
{+block}
.kjavis.dk/wp-content/uploads/20*/Cykelgaarden-1.png
{+block}
.kjavis.dk/wp-content/uploads/20*/930X120_
{+block}
.kjavis.dk/wp-content/uploads/20*/vvs-eks.png
{+block}
.kjavis.dk/wp-content/uploads/2025/04/Byg.png|
{+block}
.kjavis.dk/wp-content/uploads/2025/01/breg.png|
{+block}
.kjavis.dk/wp-content/uploads/20*/930x180_
{+block}
.kjavis.dk/wp-content/uploads/20*/Benedikte-1.png|
{+block}
.kjavis.dk/wp-content/uploads/20*/Munkebo-kro.png|
{+block}
.kjavis.dk/wp-content/uploads/20*/20-3.jpg|
{+block}
.kjavis.dk/wp-content/uploads/20*/Topann-
{+block}
.kjavis.dk/wp-content/uploads/20*/ellinge4.png|
{+block}
.www.hvidovreavis.dk/media/*/hvidover-*-1080x1080.
{+block}
.nummeruke.no/*-banner.
{+block}
.klokkeonline.no/img/hac
# — — — — — — —
# 🇳🇴：Filtjener- eller nettstedsspesifikke oppføringer med kilder
# 🇳🇴🏞：Filtenar- eller nettstadsspesifikke oppføringar med kildar
# 🇩🇰：Filserver- eller webstedsspecifikke indførsler med kilder
# 🇬🇧：Fileserver or site-specific blocking rules with sources
# bilasolurIS (03/05/2020)
/lykill_banner
{+block{btNO}}
{+block}

{+block{https://newsbreak•dk/a01-problemer-hos-tdc-maaske-kan-du-ikke-ringe-01072020/}}
{+block}
.images.sprinklecontent.com/*.amazonaws.com%2Fimages%
{+block{https://github.com/AdguardTeam/AdguardFilters/issues/67358#issuecomment-724888304}}
{+block}

# buildingsupplyNO, maskinregisteretNO, metalsupplyNO, plastforumNO
{+block}
.f.nordiskemedier.dk/*.gif
{+block{building-supplyDK}}
{+block}
.f.nordiskemedier.dk/banner
# metalsupplyNO, licitationenDK
/.*://f\.nordiskemedier\.dk/2[a-z0-9]{12,}\.(jpe?g|png)((\?|&).*)?$/
# viivillaNO (10/11/2020)
{+block}
.bcm.interactives.dk/script/
# adressaNO (10/11/2020)
{+block}
.static.polarismedia.no/*/cxense.js
{+block{https://github.com/uBlockOrigin/uAssets/issues/13661 (11/06/2022)}}
{+block{https://github.com/DandelionSprout/adfilt/issues/968}}
{+block}
.finn.no/distribution-front/external/carousel
{+block{https://github.com/DandelionSprout/adfilt/issues/983}}
.no/api/unit-image?config=
{+block{artoDK}}
{+block}
.artodata.net/site/ads/
# inderoyningenNO (20/08/2024)
# flashscoreDK (06/02/2024)
{+block}
.content.livesportmedia.eu/api/v*/banners
# fotballenEU (29/03/2025)
eu/annonse/
{+block}
.kindredplc.com/ad.
{+block}
.media.comeon.com/tracking.
{+block}
.media.folkeautomaten.com/tracking.
{+block}
.media.getlucky.com/tracking.
# politikenDK (08/02/2025)
aj2*.online/
aj2*.bid/
# skagensavisDK (30/05/2025)
/wp-content/uploads/i123_ads
# hvidovreavisDK (30/05/2025)
.dk/media/*-topbanner-
# — — — — —
# 🇳🇴：Generelle oppføringer med kilder
# 🇬🇧：Generic entries that have sources
# framtiaNO, sovestenNO, arendalstidendeNO, bil24NO, 730NO, frettatiminnIS, oppNO, melkoghonningNO
# Exceptions: balladeNO
{+block{https://www•totensblad•no/2019/nyheter/forsynte-seg-gradig-av-medaljene-i-nm/}}
{+block{arendalstidendeNO}}
{+block{https://www.langrenn.com/cppage.6250314-1743.html}}
{+block{bobilverdenNO}}
# norskenettsiderNO, svaNO
{+block{https://www•diskusjon•no/topic/1760306-ogs%C3%A5-onecall-lanserer-rollover-av-data/}}
{+block{tv2NO}}
{+block{https://kulturplot•no/synspunkt/2020/hva-er-malet-for-kultur-i-regionreformen}}
{+block{https://www•dagbladet•no/mat/spaghetti--la-capri-italienerne-liker-sausen-men-n-ting-far-slakt---dette-er-ikke-pasta/67659821}}
# portalFO (09/05/2020)
{+block{jyllands-postenDK}}
# buildingsupplyNO, maskinregisteretNO, metalsupplyNO, plastforumNO, retailnewsDK
# retailnewsDK (11/09/2020)
{+block{n247NO}}
{+block{healthtalkNO}}
{+block{appetittNO}}
{+block{ekstrabladetDK}}
# nabNO (Only shown if cookies are accepted; 18/08/2020)
# Bet365 widget triggered for Norwegian audiences only
# borsenNO (08/10/2020)
{+block{https://www•nettavisen•no/3424050834.html (24/11/2020)}}
# reavisaNO (06/12/2020)
# ytresognNO (16/12/2020)
# nettavisenNO (25/12/2020)
# aoNO (28/12/2020)
# keldanIS (05/01/2021)
# madridistaDK (21/04/2021)
/banners/casinotop
# gnavergalleriDK (along with ~60 affiliates sites)
{+block{https://github.com/DandelionSprout/adfilt/issues/233}}
.galleri.dk/content/images/fixed
# solDK (25/04/2021)
# bilgalleriDK (25/04/2021)
# forum.ipmsnorge.org (24/05/2021)
# tipsbladetDK (15/06/2021)
# solNO (22/09/2021)
# vesterbrolivDK, vafoDK, amagerlivDK
{+block{https://github.com/uBlockOrigin/uAssets/issues/13224}}
# rett24NO (13/06/2022)
# metalsupplyNO, licitationenDK (08/03/2023)
{+block{https://www•licitationen•dk/article/view/900259/efter_entreprenors_konkurs_river_106_ufaerdige_huse_ned_i_hojetaastrup (08/03/2023)}}
# maskinregisteretNO (08/03/2023)
# eikernyttNO (18/05/2023)
# Various now-dead Frettabladid subdomains
# migogkbhDK (22/06/2023)
# digitalt.tv (08/09/2023)
# h-avisNO (11/12/2023)
# skessuhornIS (29/12/2023)
{+block{solNO}}
# www•qxl•no
# www•vtb•no
{+block{vafoDK}}
{+block{reelligestillingDK}}
# www•rbnett•no
# www•op•no
{+block{journalistenDK}}
# www•altomfotball•no
{+block{dvIS}}
{+block{btNO}}
# latterkula•no/se-streamerne-som-vinner-store-gevinster-mens-de-streamer-live/
# www•latterkula•no/artikler/
# www•mbl•is/frettir/
{+block{adressaNO}}
{+block{https://nyheder.tv2•dk/2021-02-04-soennerne-saa-frem-til-en-arv-fra-deres-far-efter-mange-aars-lidelser-indtil-han-giftede (04/02/2021)}}
# kkNO, solNO
# (Exception：https://github.com/AdguardTeam/AdguardFilters/issues/58527)
# historienetNO, natgeoNO, komputerNO
{+block{qxlNO}}
# gamerNO, veier24NO, atNO, portenNO, insidetelecomNO, elektronikkbransjenNO, tu.no, digi•no
# demokratenNO, avisa-hordalandNO, blvNO, gatNO, lpNO, osogfusaNO, raumnesNO, setesdolenNO, sunnhordlandNO, vaksdalpostenNO, vtbNO
{+block{baNO}}
{+block{https://github.com/DandelionSprout/adfilt/pull/53}}
{+block}
.services.api.no/api/bazaar
{+block{aftenbladetNO}}
{+block{avisalofotenNO}}
# blv•no/nyheter/kan-bruke-23-millioner-pa-the-whale-undersokelsene
{+block{https://www•aftenposten•no/sport/sjakk/i/4qKxMg/carlsen-overbeviste-verdensmestertakter}}
{+block{https://www•aftenposten•no/sport/sjakk/i/0nyKLG/sjakkstjernen-mistet-kona}}
# aftenpostenNO (Mobile useragent)
{+block{https://www•brannmannen•no/brann/store-utfordringer-ved-togulykken-pa-asta/}}
85.17.76.181
{+block{krs247NO}}
{+block{lskNO}}
{+block{https://www•budstikka•no/}}
# e24NO, aftenbladetNO, syslaNO
{+block{https://www•austurfrett•is/frettir/lagt-smithlutfall-a-austurlandi (15/04/2020)}}
{+block{https://fiskur•fo/gitte-henning-1-landar-i-maloy (09/05/2020)}}
.fo/css/img/banner2x1.png
{+block{https://www•dagsavisen•no/nyheter/verden/1.1731911 (18/06/2020)}}
{+block{https://www•nordlys•no/egon-i-tromso-evakuert-tok-fyr-i-en-ovn/s/5-34-1326807 (10/07/2020)}}
# advokatbladet.no; https://gardsdrift•no/maskiner-potet-fagdag/folksomt-under-potato-scandinavia/185668 (16/08/2020)
# kimbinoNO, kimbinoDK (13/09/2020)
# lokal-avisaNO, ringsakernNO (19/09/2020)
# gjoviksbladNO (19/09/2020)
# midtjyllandsavisDK, herningfolkebladDK, ikast-brandenytDK (30/09/2020)
# godstartDK, solDK (30/09/2020)
{+block}
.ni.dk/ni-news/*feed/*-bottom.html
# fyensDK, stiftenDK, jvDK, dagbladet-holstebro-struerDK, hsfoDK (30/09/2020)
{+block{https://www•nutiminn•is/menn-is/spilagaldur-ruglar-i-hausnum-thinum-varud-gaeti-fengid-thig-til-ad-trua-a-galdra-myndband/}}
# dagsavisenNO (30/05/2021)
# aftenpostenNO, hockeymagasinetDK, l-aNO, aftenbladetNO (30/10/2020)
# btNO, byasNO, aftenbladetNO (30/10/2020)
# costumeNO, costumeDK (09/11/2020)
# boligplussNO (09/11/2020), womenDK
# ytresognNO (16/12/2020)
^.*_980banner_
# ambulanseforumNO (26/12/2020)
# fyensDK, faaDK, stiftenDK, jvDK, amtsavisenDK, vafoDK, viborg-folkebladDK, hsfoDK, frdbDK, folkebladetlemvigDK, dbrsDK, dagbladet-holstebro-stuerDK, helsingordagbladDK (02/01/2021)
# forum•doktoronline•no (06/01/2021), forum•klikk•no, forum.kvinneguiden•no
# nettavisenNO (20/01/2021)
{+block{https://www•helsenett•no/spor-oss/har-du-smabarn/50657-svstadig-tilbakevendende-forkjolelsehostefeber.html (10/02/2021)}}
{+block{https://www•tronderdebatt•no/vet-regjeringen-at-det-bor-folk-langs-grensen-nord-i-trondelag/o/5-122-18453 (20/03/2021), baNO}}
{+block{https://viralefilmer•no/norske-henry-78-kjopte-superbil-med-700-hestekrefter-til-43-millioner/ (25/03/2021), eavisaNO}}
{+block{https://www•terrengsykkelforumet•no/ubbthreads.php?ubb=showflat&Number=2453543 (31/03/2021), terrengsykkelNO}}
# nettavisenNO (04/04/2021)
# gnavergalleriDK (along with ~60 affiliates sites; 21/04/2021)
{+block{nidarosNO}}
{+block{dagsavisenNO}}
# elbil24NO, viNO (21/06/2021)
# farmatidNO (16/11/2021)
{+block{https://radioh•no/norsk-opphenting-mot-nederland-sikret-vm-kvartfinale-storm-i-kastene/ (14/12/2021)}}
# nordlysNO, anNO (19/06/2022)
# nidarosNO (22/02/2023)
# jyllands-postenDK (22/03/2023)
# forum•kvinneguiden•no (Mobile user agent; 05/04/2023)
# Various now-dead Frettabladid subdomains from 2020
{+block{https://www•aftenposten•no/sport/fotball/i/QoP7KA/spansk-fotballstreik-fortsetter (26/12/2023)}}
# e24NO (Mid-December 2023)
{+block{https://heimildin.is/greinar/?label=1 (09/10/2024)}}
# euroinvestorDK (13/11/2024)
{+block{https://www•avvir•no/samegiella-ja-mearkagiella-vuosttasgiellan/}}
{+block{https://ugenr•dk/kalender (03/12/2024)}}
# dagensDK/NO articles
# flashscoreDK (06/02/2025)
# gatNO, drivaNO (18/02/2025)
{+block{https://www•tv2•no/livesport/vintersport/oversikt (09/03/2025)}}
# TV2dk's feeds on phones (11/03/2025)
{+block{abcnyheterNO}}
# gulesiderNO, degulesiderDK, krakDK
# arendalstidendeNO, sorlandsavisenNO, eirikurjonssonIS
# building-supplyDK, licitationenDK, jernindustriDK
{+block{veier24NO}}
# migogaarhusDK, migogaalborgDK, migogkbhDK
# frolendingenNO, ytringenNO (20/05/2025)
# flaDE (30/05/2025)
{+block{https://www•kanalfrederikshavn•dk/vis/nyhed/oslo-faergernes-skaebne-i-frederikshavn-afgoeres-foerst-efter-sommerferien}}
# seoghoerDK (01/07/2025)
# spill•abcnyheter•no (27/07/2025)
# — — — — — — —
# 🇳🇴：Oppføringer med spesielle omstendigheter
# 🇬🇧：Entries with special circumstances
{+block}
.samimag.no/wp-content/uploads/2019/11/Screenshot-2020-03-21-at-12.40.32.png
{+block{https://www•aftenposten•no/sport/i/kR20OL/uno-x-soeker-om-worldtour-lisens-en-droem-som-har-modnet-over-tid (03/09/2022)}}
# Should not have ":not" + ":empty" added to it due to costume•no
{+block{https://github.com/uBlockOrigin/uAssets/issues/28638}}
# — — — — — — — — —
# 🇳🇴/🇩🇰：IP-adresser
# 🇳🇴🏞：IP-adressar
# 🇬🇧：IP addresses
3.248.18.175
35.227.231.163
45.58.146.154
82.196.13.38
82.221.81.9
178.79.136.45
# politikenDK (08/02/2025)
65.21.200.49
# 🇳🇴/🇩🇰：——— Sporingsfiler ———
# 🇳🇴🏞：——— Sporingsfilar ———
# ❄：——— Guorrafiilaid ———
# 🇬🇧：——— Tracker files ———
{+block{https://github.com/DandelionSprout/adfilt/pull/699}}
{+block}
.s.api.no/mittari/c/article/*/sectionId/*.gif
{+block{https://github.com/uBlockOrigin/uAssets/issues/18880}}
.no/app/aas
aas.*.no/a/
# 🇳🇴：——— Tomme skillebokser ———
# 🇩🇰：——— Tomme adskillerbokser ———
# 🇳🇴🏞：——— Tomme skiljeboksar ———
# 🇮🇸：——— Tóma skilirammar ———
# 🇬🇧：——— Empty divider spaces ———
# Was supposed to be synced often with https://raw.githubusercontent.com/DandelionSprout/adfilt/master/EmptyPaddingRemover.txt, which has not been the case.
# aİD (Phone user agent)
{+block{https://github.com/AdguardTeam/AdguardFilters/issues/189667}}
{+block{https://www•dagsavisen•no/sport/2024/10/31/kfum-oslo-var-uhyre-naer-et-finaleran/}}
# 🇳🇴：——— Distraherende bakgrunnsbilder ———
# 🇩🇰：——— Distraherende baggrundsbilleder ———
# 🇮🇸：——— Truflanda baksýnsmyndir ———
# 🇬🇧：——— Distracting background images ———
{+block}
.images.media.xxlsports.com/images/h90/h9d/9339713159198/bg.jpg
{+block}
.platekompaniet.no/assets/img/background.png
{+block}
.pepcall.no/wp-content/uploads/2015/04/bakgrunn-forside.jpg
{+block}
.tv2.no/s/lab/2.5/p/img/tv2-background.svg
# 🇳🇴：——— Fiksing av knekte sider ———
# 🇩🇰：——— Fiksing af knækte websider ———
# 🇮🇸：——— Óbrot ———
# 🇬🇧：——— Unbreakage ———
# Posten's new parcel tracker, fixes the form for giving them delivery information (doorbell name/number)
{-block}
.glow.posten.no/api/tracking/*
# Makes articles that would be counted as ads anywhere else on SeHer, show up on that page.
{+block{https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-683430537}}
{-block}
.isdownorblocked.com
# ★★★ Caused by «EasyPrivacy» ★★★
# Attempting to fix a problem with voting online on Idol Norway
{-block}
.tv2.no/*/config/analytics.json
# Attempts to resolve how some frontpage articles are hard to open
{+block{https://github.com/easylist/easylist/issues/18542 (These entries are here to stay, regardless of the report's outcome.)}}
{-block}
.medlemskap.*.no
{-block}
.bestill.help.no
{-block}
.ask.antalis.
# Similar cases. I cannot in good conscience let Norwegian and Danish users be affected by entry patterns like these, even less so after AdGuard Tracking Protection Filter was removed from uBO's opt-ins.
{-block}
.app.*kino.no
{-block}
.images.medlem.
# Bank login problems
# ★★★ Caused by «EasyList – Social Widgets», if I recall correctly ★★★
{+block{https://github.com/ryanbr/fanboy-adblock/issues/1261}}
{+block{https://github.com/easylist/easylist/issues/7805 (05/05/2021)}}
# ★★★ Caused by «Fanboy's Annoyances List» and «EasyList Cookie List» ★★★
{+block{https://github.com/ryanbr/fanboy-adblock/issues/1243}}
{+block}
.ktg-content.cdn.prismic.io/api/*/documents/*(my.newsletter_popup.uid
{+block{https://github.com/ryanbr/fanboy-adblock/issues/1339}}
{+block{https://github.com/ryanbr/fanboy-adblock/issues/1468}}
{+block{https://github.com/easylist/easylist/issues/12067#issuecomment-1132797711}}
{+block{https://github.com/easylist/easylist/issues/20085}}
# ★★★ Caused by «Fanboy's Enhanced Blocking List» ★★★
{+block{https://github.com/DandelionSprout/adfilt/discussions/779#discussioncomment-5962141}}
# ★★★ Caused by «EasyList» ★★★
{-block}

{-block}
.bluesnews.no/Files/Images/annonser
{-block}
.lnk.no/wp-content/uploads/*/ads
{-block}
.marketingfabrikken.dk/page-data/google-ads/page-data.json
{+block{https://raw.githubusercontent.com/hkarn/scandinavianlist/master/scandinavianlist/scandinavianlist_whitelist.txt}}
# Forum feeds in the upper right of articles
# Makes 1p info banners show up correctly
{+block{https://github.com/uBlockOrigin/uAssets/issues/11546}}
{+block{https://github.com/uBlockOrigin/uAssets/issues/13907}}
{+block{http://sosialurin•fo/news-detail/steypafinala-vilhelm-og-rogvi-a-ruv1-fra-klokkan-1630}}
# ★★★ Caused by «I Don't Care About Cookies» (Its maintainer couldn't reproduce it) ★★★
# Fullpage uncloseable overlay when browsing around on Telenor Norway's TV section
# ★★★ Unknown cause ★★★
{+block{https://github.com/DandelionSprout/adfilt/issues/67}}
{+block{https://new•reddit•com/r/uBlockOrigin/comments/gye2f2/cant_watch_videos_on_a_specific_website_with/ft9zlse/}}
{-block}
.cmp.ekstrabladet.dk/get_site_data
{-block}
.ad.amediakreativ.no/widgets/stillingskarusell
# ★★★ Caused by «Peter Lowe's Ad and tracking server list» ★★★
# ★★★ Caused by «Dan Pollock's hosts file» ★★★
# ★★★ Caused by «AdGuard Cookie Notices filter» ★★★
{-block}
.glassoginterior.no/css/modules/consent.css
# ★★★ 🇳🇴：Forårsaket av «AdGuards spionvarefilter» ★★★
# ★★★ 🇬🇧：Caused by «AdGuard Tracking Protection Filter» ★★★
{+block{https://github.com/AdguardTeam/AdguardFilters/issues/209205}}
{-block}
.tv2.no/*/snowplow/*
# 🇳🇴/🇩🇰：Anti-'CPU-massakrering'
# 🇮🇸：And-örgjörvislatrun
# 🇬🇧：Anti-'CPU slaughtering'
# 🇳🇴：——— Norsk Tipping, inkl. tvilsomt motiverte lottoreklamer (Noen ikke-påtrengende tippereklamer er greit nok i mine øyne) ———
# 🇩🇰：——— Norsk Tipping, inkl. nogle tvivlsomt motiverede lottoreklamer (Nogle ikke-påtrængende sportstipsreklamer er akseptabelt i mine øjne) ———
# 🇳🇴🏞：——— Norsk Tipping, inkl. tvilsamt motiverte lottoreklamar (Ein håndfull ikkje-påtrengande tippereklamar er i orden for meg) ———
# 🇬🇧：——— Norsk Tipping, incl. poorly motivated lotto ads (A few non-pushy football pool ads are fine in my book) ———
{+block}
.tipster.no/embed
{+block{https://www•nettavisen•no/}}
{+block{https://www•ba•no/s/5-8-1221171}}
{+block}
.vg.no/vgc/pool/tipster.png
/pustehullet/betting-header.png
{-block}
.oddstips.norsktippingpartner.no
# nidarosNO (02/12/2021)
# h-avisNO (11/12/2023)
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-7794535}}
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-7865350}}
{+block{https://www•nettavisen•no/sportspill/her-er-tallene-som-vil-fa-liverpool-fansen-i-godt-humor/s/5-95-1529066}}
# 🇳🇴：Oppføringer for ytre-høyre-nettsteder. Støtte for disse nettstedene er begrenset, og de fleste nye oppføringer som blir foreslått for dem vil bli ordrett godkjent.
# 🇮🇸：Skráningar fyrir ytrihægri-vefsiður. Stuðningur við þessar síður er takmarkaður, og flestar nýjar skráningar sem mælt er með fyrir þær verða innifalin orðrétt.
# 🇬🇧：Entries for far-right websites. Support for these sites is limited, and most new entries that are suggested for them will be accepted verbatim.
{+block{https://github.com/uBlockOrigin/uAssets/issues/16138}}
{+block{https://github.com/ryanbr/fanboy-adblock/issues/1405}}
{-block}
.politainment.no*/cookieconsent.min.js
# 🇳🇴：Falske innlastinger som sløser bort tid
# 🇩🇰：Falske indlastinger, der søler bort tid
# 🇬🇧：Fake loading screens that waste time
# adressaNO (02/12/2020)
collector.schibsted.io/
# "Generic Hide"
# Fixed in better ways in AdGuard Base and uBlock Filters, but is needed for ABP
# 🇳🇴：Hvitelisteoppføringer for å unngå å trigge anti-reklameblokkeringstiltak (Slike hvitelistinger er fullt tillatt av Adblock Plus som det er meg bekjent)
# 🇬🇧：Allowlist entries to avoid triggering anti-adblock measures (Such allowlistings are fully allowed by Adblock Plus from what I'm aware of)
{-block}
.www.tv2.no/s/js/ads.js
{-block}
.sumo.cdn.tv2.no/ads
{+block{https://github.com/AdguardTeam/AdguardFilters/issues/121422}}
{-block}
.v.fwmrm.net/ad/g*:MTG_Play_
# gamerNO (27/07/2025)
{-block}
./vendor/_a/gpt.js?
# 🇳🇴：Oppføringer som også er tilstede i «AdGuards hovedfilter / AdGuard Base Filter», for de som bruker ABP og AdBlock, eller som ikke har tatt seg bryet å bruke 8 sekunder på å skru den på i uBlock Origin.
# 🇩🇰：Opføringer som også er tilstede i «AdGuard Basisfilter / AdGuard Base Filter», for de der bruger ABP og AdBlock, eller der ikke har tatt seg bryd at bruge 8 sekunder på at abonnere på den i uBlock Origin.
# 🇬🇧：Entries that are also present in AdGuard Base Filter, for those who use ABP and AdBlock, or who haven't felt a need to spend 8 seconds to subscribe to it in uBlock Origin.
# Starting with 10May2024v4, only entries from newer than #50000 in AdGuard Filters' issue section will be included in this section, to avoid very outdated entries.
widget.tippebannere.no
{-block}
.borsen.dk/themes/borsen.dk/js/dfp.js
{-block}
.bt.dk/build/prebid-ads-advertisement_adbanner.*.js
{-block}
.cdn.maskinbladet.dk/*assets/templates/*/img/adblocker/ads.png
# jyllands-postenDK (09/07/2020)
{+block{specificTXT}}
{+block{https://github.com/uBlockOrigin/uAssets/issues/26263 (02/12/2024)}}
# Syncing from 166942 onwards (14/04/2025)
# 🇬🇧：Entries that are also present in «uBlock Filters», for those who use ABP and AdGuard
# ——————————————————————————————————————————————————————————————————————————————————————————
# 🇳🇴：Svindelnettsteder og virusnettsteder (Ikke besøk dem hvis du har dine datamaskiner og lommebøker kjært)
# Rask leksjon: Mange svindelnettsteder bruker adresser som ligner på adressene til store nettsteder, men som inneholder tilfeldige ekstra smådetaljer som gjør dem til en helt annen adresse. "||vg.no." vil blokkere vg.no.iphone-svindel-eksempel.xyz, men ikke vg.no eller vg.no/sport
# 🇩🇰：Fupsider og virussider (Besøg dem ikke, hvis du sætter pris på dine computere og tegnebøger)
# 🇮🇸：Svindlsidur og vírussidur (Ekki heimsæk þeim ef þér líkar þinni tölvur og peningaveskur)
# 🇬🇧：Scam sites and virus sites (Do not visit them if you value your computers and wallets)
# Quick 101: Many scam sites use addresses that resemble those of major sites, but which contain random extra tidbits that make them a whole different address. "||vg.no." will block vg.no.iphone-scam-example.xyz, but not vg.no or vg.no/sport
/begrensede-tilbudet/*
/KiwiErbjudanden1/*
.gratis-reisebilletter.
102.112.2o7.net/
52.216.146.90
92.42.104.146
.jimmychoostore.top/
look-like-star.myshopify.com/
.marked.no/
.mrcal365.com/
.pensjonistferie.no/
.postuksus.com/
.replicapatekphilippe.com/
.replicarolexyachtmaster.com/
.secureriches.com/
.tromselementbygg.no/
ultimate-tech-products.myshopify.com/
.norskposten.com/
.oslo-tannlegene.no/
.y6.no/
.havfruen4220.dk/
.srilanka.no/
.innboks.info/
.pearlandcarpetcleaner.com/
/?finn.no/login
# 🇬🇧：Copied over from «Dandelion Sprout's Anti-Malware List»
.fredfiber.no/
.gogle.net/
# 🇬🇧：Scam domains as reported in https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-988127908
{+block{https://www•tek•no/i/lVeQAe/}}
{+block{https://www•nkom•no/aktuelt/ikke-trykk-pa-lenker-i-sms--for-du-er-helt-sikker/}}
.eccolabgroup.com/
.galerijajava.ba/
.p-stn.net/
# Fake Gymshark webshops
# E-mail tips
s.free.fr/
trmff.wpengine.com/
212.27.60.108
.790northsierrabonita.com/
dnnbcorporat*.mine.nu/
eltlnorsgogle.is-a-cpa.com/
.pestseminars.com/
.premosupplements.com/
.printablemagic.com/
.rumendia.com/
94.156.65.204
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-9075749}}
# 🇳🇴：Som nevnt i diverse nyhetsartikler om svindelsider
# 🇩🇰：Som nævnt i diverse nyhedsartikler om fupwebsider
# 🇬🇧：As mentioned in various news articles about fraud sites
{+block{https://www•tv2•no/nyheter/10493336/}}
{+block{https://www•nrk•no/norge/1.14511067}}
{+block{https://www•datahjelperne•no/verifiser-get-konto-falsk-mail/}}
{+block{https://www•datahjelperne•no/gratulerer-du-har-vunnet-en-gave-mail-svindel/}}
.liveshopdealz.com/
{+block{https://www•nrk•no/livsstil/1.14732503}}
{+block{https://www•datahjelperne•no/sparebank1-kortet-ditt-er-blokkert-mail-phishing/}}
{+block{https://www.facebook.com/viralspiralen/posts/2494251397311027}}
.addmoviesnow.com/
{+block{https://www•mm•dk/tjekdet/artikel/faarup-sommerland-advarer-mod-gratis-billetter-det-er-spam-og-fup}}
{+block{https://www•mm•dk/tjekdet/artikel/det-er-fup-heller-ikke-denne-gang-giver-legoland-5-gratis-billetter-vaek}}
{+block{https://www•mm•dk/tjekdet/artikel/ogsaa-chili-klaus-maa-staa-model-til-falske-annoncer}}
.hcliips.com/
{+block{https://www•nrk•no/troms/1.14788086}}
.geometra-bologna.it/
{+block{https://www•nrk•no/nyheter/1.14793929}}
.sky.gs/
{+block{https://www•online•no/sikkerhet/falsk-online-nettside}}
.is-a-personaltrainer.com/
{+block{https://nyheder.tv2•dk/krimi/2020-02-11-politiet-advarer-mod-svindler-smser-forsoger-at-fa-billede-af-nemid}}
{+block{https://www•faktisk•no/faktasjekker/vw8/erik-gikk-fra-arbeidsledig-til-millionaer-pa-8-uker}}
{+block{https://www•mm•dk/tjekdet/artikel/fup-artikel-hun-er-tiltalt-for-millionsvindel-men-nu-pludselig-loesladt}}
{+block{https://www•tv2•no/nyheter/11516670/}}
{+block{https://www•datahjelperne•no/posten-informerer-deg-om-forsendelsen-din-mail-svindel/}}
{+block{https://www•datahjelperne•no/skatteberegning-mail-svindel/}}
{+block{https://www•datahjelperne•no/olav-thon-facebook-svindel/}}
{+block{https://www•datahjelperne•no/vipps-sms-svindel/}}
{+block{https://www•datahjelperne•no/hvit-bjorn-river-kvinne-i-stykker-facebook-spam-oppdatert/}}
.vidcopa.me/
{+block{https://www•adressa•no/pluss/nyheter/2020/08/26/Kristofer-Hivju-V%C3%A6r-s%C3%A5-snill-og-slutt-22527944.ece}}
.smallrise.com/
{+block{https://www•datahjelperne•no/coop-du-har-fatt-nye-kuponger-mail-svindel/}}
{+block{https://www•datahjelperne•no/elkjop-kontaktforsok-mail-svindel/}}
{+block{https://www•datahjelperne•no/sparebank-1-din-tilganger-er-blokkert-svindel/}}
.cionialessio.it/
{+block{https://www•dinside•no/okonomi/advarer-mot-falsk-facebook/72891041}}
{+block}
.sites.google.*/halaman-muka
{+block{https://www•datahjelperne•no/norske-facebook-profiler-misbrukes-i-svindel/}}
{+block}
.sites.google.com/view/truls-svendsen
signup-*vpns.com/
{+block{https://www•datahjelperne•no/telenor-din-faktura-mislyktes-svindel/}}
{+block{https://www•datahjelperne•no/eurocard-falsk-epost-faktura/}}
{+block{https://www•datahjelperne•no/eika-falsk-epost-svindel/}}
{+block{https://www•nrk•no/norge/1.15235615}}
{+block{https://www•datahjelperne•no/er-det-deg-facebook-video-spam/}}
.cinefique.com/
/(https?://)?[a-z]{10,12}\.easy\.co(/.*)?$/
{+block{https://www•datahjelperne•no/posten-sms-svindel/}}
.niupaiba.com/
{+block{https://www•adressa•no/pluss/nyheter/2021/03/30/Ser-du-hvilken-profil-som-er-ekte-23739076.ece}}
.nordeninterior.weebly.com/
# Googling Aksel Hennie (Results for prior week) in late July 2021
# Various Google results for 'jesper buch bitcoin'
{+block{https://www•nrk•no/vestfoldogtelemark/1.15750360}}
.dundeehills.group/
{+block{https://www•adressa•no/pluss/nyheter/2021/12/04/Posten-advarer-Vi-sender-ikke-slike-tekstmeldinger-24894483.ece}}
.ozarkvillage.net/
.channawars.com/
{+block{https://www•vi•no/forbruker/ikke-trykk-pa-lenka-fra-skatteetaten/75666026}}
.melding.link/
{+block{https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-1114669106}}
{+block{https://www•kode24•no/artikkel/75980495}}
.campbell-living.com/
{+block{https://www•telia•no/kundeservice/mobil/malware-flubot-android/}}
.wxqgx123.com/
{+block{https://dinside.dagbladet•no/mobil/ikke-la-deg-friste/76730599}}
.k-yw.com/
{+block{https://dinside.dagbladet•no/okonomi/tusenvis-forsokt-lurt/76921148}}
.a2ics.eu/
.smsb.co/
{+block{https://www•tv2•no/nyheter/innenriks/advarer-om-svindel-sms-sender-aldri-slike-henvendelser/16284207/ (15/12/2023)}}
{+block{https://github.com/DandelionSprout/adfilt/issues/747}}
{+block{https://github.com/DandelionSprout/adfilt/issues/748}}
{+block{https://www•adressa•no/nyheter/trondheim/i/Moq2wR/svindlere-kaarer-vinnere-i-konkurranser-gir-en-daarlig-foelelse-aa-forklare-at-dette-bare-er-tull}}
{+block{https://www•adressa•no/nyheter/trondheim/i/69d3lL/spisesteder-rammet-det-er-forferdelig-jeg-fikk-panikk}}
.sitey.me/
{+block{https://www•tv2•no/nyheter/innenriks/olav-thon-misbrukes-i-svindelannonser-ble-feilaktig-meldt-dod/15818647/}}
.24-news.online/
{+block{https://www•tv2•no/nyheter/innenriks/advarer-ikke-klikk-pa-lenken/16040614/}}
.brugerverificering.com/
.dhl-trackng.com/
dnb-oppdater.
.linkednordersalenavigate.com/
.mobilidentitet.com/
.mobiltrygheden.com/
.mobilunderskriv.com/
.no-aut.co/
.no-bekreft.com/
.no-confir.com/
.no-erne.com/
.no-erne.live/
.no-nye.live/
.no-renovere.com/
.no-sikkerhet.com/
.no-update.live/
.no-updater.live/
.start-myaltinn.com/
.no-oppdatere.
179.43.189.62
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-7694946}}
easypark-
74.119.239.234
162.241.194.206
# IP addresses of servers notorious for hosting many of the sites above
51.195.133.131
66.206.3.34
82.118.242.69
136.243.73.30
138.201.126.227
156.236.126.173
196.196.230.76
167.71.49.177
134.209.82.119
154.213.16.136
158.247.212.220
165.227.168.212
132.148.220.142
104.160.10.
165.231.154.
167.99.196.225
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-7872103}}
.betzykrisesenter.no/
.citra2010oslo.no/
.digiter.no/
.easydisplay.no/
.kjaerra.no/
.kontrast1.no/
.norskmatkultur.no/
.norskoffroadteknikk.no/
.nyematoghelse.no/
.securmarksykkel.no/
.thecoolgirl.no/
.topshineauto.no/
.vossblues.no/
.yttersiden.no/
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-7873648}}
monetrizer*.
38.180.96.244
{+block{https://sol•no/81812194/ / https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-10360231}}
.acc-inf.com/
.acc-ntfix.com/
.accessmyretur.com/
.adgangsikret.com/
.aib-loginsecure.com/
.aktivalia-ntflx.com/
.app-netfiix.com/
.be-lnfo.com/
.be-sms.com/
.billing-invalid.com/
.billingservice02-myinfo.com/
.binance-bedring.com/
.borgerpost-mitdk.com/
.bov-userid-application.com/
.bov-userid.com/
.businessonline-webchat.com/
.byra-altinn.com/
.ca-srvpayment.com/
.chase-verify-activity.com/
.city-parking-ssl1.com/
.clientnetflixcenter.com/
.co-accountswitch.com/
.co-switchaccount.com/
.comm-bankverify.com/
.connection-info.com/
.dhl-aus-id.com/
.digitalbrevpost.com/
.digitalemitdportal.com/
.directdigital-services.com/
.disney-abonnements.com/
.disney-facturations.com/
.disneyplus-tv.com/
.dplus-pixar.com/
.e-boksinfor.com/
.e-interactransfer.com/
.earnifi-claiming.com/
.easywebauthentication-td.com/
.ebanking-userid.com/
.edksundportal.com/
.eportalsundhed.com/
.esundinfo-dk.com/
.fakturalosning.com/
.flix-area.com/
.flix-request.com/
.fornyeportalen.com/
.gateway-kraken.com/
.gmailsetupinfo.com/
.helpnet-device.com/
.indtoll.com/
.indtollswebt.com/
.intrumtunnistus.com/
.itmitsikkert-nu.com/
.itsme-support.com/
.kvkregister.com/
.levering-myups.com/
.lnfoskonto.com/
.mijnups-pakket.com/
.min-altinnboks.com/
.min-borgerepost.com/
.minaltinn-info.com/
.minaltinninfo.com/
.minbrugerpost.com/
.minsikreboks.com/
.minsundhed-tjek.com/
.missed-id.com/
.mit-digitalopna.com/
.mitborgere.com/
.mitborgereportal.com/
.mitdigitalborger-post.com/
.miteinfo-nu.com/
.mitld-forholdsregler.com/
.mobilepay-finland.com/
.mobilpay-fi.com/
.my-netflixssl1.com/
.my-subscriptions.net/
.my02-billinghelp.com/
.myaccount-billing-details.com/
.myaccountneftlixssl1.com/
.myups-pakket.com/
.myups.express/
.myupsdelivery-ssl1.com/
.nemlogindigitalbrevkasse.com/
.netfiix-abo.com/
.netfiix-app.com/
.netfiixtv.com/
.netflix-bhr.com/
.netflx-tv.com/
.netfx-acc.com/
.netfx-pagos.com/
.ney-acc.com/
.nflix-management.com/
.nflix-reactivacion.com/
.ntfx-acc.com/
.onetime-bonus.com/
.online-connection-review.com/
.onlinehelpcenetre.com/
.optankning.com/
.parking-onlinepayment.com/
.parking-ticket2024.com/
.parkpay-reminder.com/
.parkpay-tickt.com/
.parkticket-pay.com/
.pay-ticket2024.com/
.payement-renew.me/
.paynow-ticket.com/
.portalsikkerhet.com/
.pt-netfiix.com/
.rebill-netflix.com/
.recover-dk.com/
.regions-services.com/
.regions-verification.com/
.report-action.com/
.reschdl-myups1.com/
.reschedule-myups.com/
.restore0-2account-service.com/
.ri-myorder.com/
.saaq-click.com/
.safe-secured-transfer.com/
.santandersecurept.com/
.secureaccountcredentials.com/
.sessionpaused-requestexpired.com/
.sikker-digitaipost.com/
.sikker-vlpps.com/
.sikkeradmin.com/
.sikkerbekreftelse.com/
.sikkerinngang.com/
.sikkerportal-altinn.com/
.sikkerportal-boks.com/
.sikkertilgang-altinn.com/
.sociale-assurance.com/
.spotfy-regulation.com/
.ssl-app.com/
.sslh1-myparkingticket.com/
.sslnetflix.com/
.sundhed-einfoportal.com/
.sundhed-tjek.com/
.sundhedportaldk.com/
.tax-binance.com/
.techsantandersecure.com/
.trackingfindups.com/
.trackingpackage.express/
.tsbconnect-verification.com/
.tsbsecurity-online.com/
.tv-netfiix.com/
.ups-packaging.delivery/
.ups-rescheduledelivery.com/
.ups-upsnow.com/
.ups1-reschdl.com/
.upsbezahlung.com/
.upsreschedule-uy.com/
.usaa-verify.com/
.user-amazon-id.com/
.usps-fast.club/
.vat-reschedule.com/
.verification-no.com/
.wf-securelogin.com/
.wisehelpcentre.com/
193.143.1.45
193.143.1.214
193.143.1.217
193.143.1.
.modificationdesignate.com/
xss.my.id
85.159.213.158
.nestnose.com/
.inquisitivebed.info/
# 🇳🇴：E-post-spammere (Falsk DHP, osv.)
# 🇬🇧：E-mail spammers (Fake DHP, etc.)
wirexapp.africa.com/
tachyoniums.eu.com/
{+block}
.storage.googleapis.com/absales
healtheweb.co.uk/
.appearspacex.de/
195-242-152-122.static.hvvc.us/
195.242.152.122
.mygoodmerch.com/
{+block{https://www•tv2•no/nyheter/forbruker/sjokksvar-pa-epost-harreisende/17805239/}}
{+block{https://www•tv2•no/nyheter/forbruker/tenkte-shit-na-har-jeg-blitt-lurt/17474448/}}
{+block{https://www•tv2•no/nyheter/innenriks/slar-svindelalarm-trykker-pa-de-riktige-knappene/17975382/}}
{+block{https://www.tv2.no/nyheter/innenriks/raser-mot-nettside-laget-for-a-lure-folk/17976442/}}
# 🇬🇧：Pirate-product-selling stores registered by the serial scammers who go by the name of "xiang dao xin xi ji shu you xiang gong si".
.nofotballshop.com/
.nofotballstore.com/
.nodrakts.com/
.dkfodboldstore.com/
.vmfodboldtoj.com/
5.39.217.206
5.39.221.180
193.148.70.153
# 🇳🇴：Falske nettapoteker
# 🇬🇧：Fake online pharmacies
# 🇬🇧：Old domains stolen by casino sites
# 🇬🇧：Various postal credential fraud syndicates
.norgeposten.today/
.norwayposten.today/
.pakkeposten.today/
.post-dk.cfd/
post-nord-levering.
post-nord-receiving.
posten-nno.
.posten-track.today/
.posten-tracker.today/
posten-tracks.
.postendk.lol/
.postendsk.lat/
postenn-no.
.postennorge.today/
.postennorway.today/
.postenpakke.today/
.postenserve.today/
.postenserves.today/
.postenspor.today/
.postentrack.today/
.postentracks.today/
.postnord-24.site/
postnord-all.
postnord-confirmation.
postnord-delay.
.postnord-eco.buzz/
.postnord-eco.cfd/
.postnord-eco.sbs/
.postnord-eco.xyz/
postnord-order-
postnord-paket.
postnord-pay.
postnord-post.
postnord-se-delivery.
postnord-step.
postnord-step1.
postnord-tk.
postnord-tracks.
.postnord-update.help/
postnorde-swe.
postnordexpress.
postnordexpressdelivery-
.postnordse.asia/
postnordspara.
postnorg-dk*
.sporposten.today/
43.100.125.58
43.159.140.215
43.162.119.45
47.76.132.29
109.230.237.116
147.93.63.211
154.223.16.232
# 🇬🇧：Copied over from DNS-BH Malware Domains and verified to actually be malicious (as that list has a whole lot of false positives)
.desidert.no/
.brigitteheilmann.dk/
.storustovu.dk/
.campingnews.dk/
# 🇬🇧：Copied over from URLHaus and verified
.hagebakken.no/
.mdb.nu/
.idj.no/
1.14.61.188
.smarthouseforum.ru/
.trafikkskoleapp.no/
# 🇬🇧：Intended for Adblock Plus
# Last updated: 05April2025v1-Extension
# 🇳🇴: ——— Vindusviskere for betalte artikler (sånn at de nederste linjene i en forhåndsvisning ikke toner ut) ———
# Takk til THEtomaso (https://github.com/THEtomaso) for de fleste av disse oppføringene.
# 🇩🇰: ——— Vinduesviskere for betalte artikler (så de sidste par linjer i en forhåndsvisning ikke falder ud) ———
# Tak til THEtomaso (https://github.com/THEtomaso) for de fleste af disse regler.
{+block{🇬🇧: ——— De-blurrers for paid articles (so that the last few lines of a preview doesn't fade out) ———}}
# Thanks to THEtomaso (https://github.com/THEtomaso) for most of these entries.
{+block}
.dagligvarehandelen.no/sites/all/themes/custom/ledelseas/gfx/veil.png
# 10/02/2024
{+block{https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-8603702}}
# dagbladetNO, elbil24NO
# digi.no, tu.no, medier24.no, porten.no
{+block{https://www•klikk•no/side3/vimenn/viggo-bloffet-hele-norge-6857944}}
{+block{https://www•vg•no/nyheter/i/y3Mka2/ (08/04/2020)}}
{+block{https://www•vg•no/nyheter/innenriks/i/3JbRzv/ (09/04/2020)}}
{+block{https://www•vestnesavisa•no/2024/nyheiter/hald-pa-hatten-i-dag-kan-det-blese-godt/ (24/10/2024), h-a•no, lokal-avisa•no, ringsakern•no, stangeavisa•no}}
# 🇳🇴/🇩🇰: ——— Anti-anti-reklameblokkering ———
# 🇮🇸: ——— And-and-auglýsingshindrun ———
{+block{🇬🇧: ——— Anti-anti-adblocking ———}}
.elderlyscissors.com/
{+block}
.vg.no/cnp-assets/src/sites/vg/components/AdblockModal
# Also fixed in "uBlock Filters - Privacy", but is added to this list as well, because it serves to remove AAAB notices on various pages (especially when "uBlock Filters" is turned on).
# aftenpostenNO, abcnyheterNO, recordereDK, gastrofunDK, fyensDK, tilbudsukenNO, viborg-folkebladDK, gaffaDK, jvDK
{+block{https://github.com/uBlockOrigin/uAssets/issues/8648}}
{+block{https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/305}}
{+block{https://www•findroommate•dk/vaerelser/302142/stort-lyst-vaerelse-taet-paa-aarhus-i-viby-centrum (17/12/2021)}}
{+block{https://github.com/uBlockOrigin/uAssets/issues/13495}}
# The green "Abonner" button in the upper right appears to work perfectly even with this entry, and the entry does not cause the Plus article bodies to appear either, so I feel I'm on safe enough grounds on this one.
# Borrowed from "uBlock Filters — Ads" (31/10/2024)
{+block{🇬🇧: ——— Not actually AAB, but would've caused fatal breakage in ABP ———}}
{+block{🇬🇧: ——— An unusual entry, but a needed entry: Aims to prevents NRK's login system on Google Translate-d pages from forcing readers who were logged in to their regular site, from being redirected from a translated page to the non-translated frontpage. ———}}
#¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤=☆=¤!
# 🇳🇴/🇩🇰: ——— Ikke for Brave Browser ———
{+block{🇬🇧: ——— Not for Brave Browser ———}}
# Last updated: 09February2022v1-Extension
{+block{https://github.com/brave/adblock-lists/issues/768 (Remove when Shield Standard Mode adds support for cosmetic filtering in default lists)}}
{+block}
.akamai.vgc.no/drfront3
