{+block}
# Version: 31August2019v1-Alpha
# Version: 310820191 (for Adblock Plus' issue report system)
# Title: 🏔️ Dandelion Sprouts nordiske filtre for ryddigere nettsider (for Privoxy)
# Translated title: Dandelion Sprout's Nordic filters for tidier websites (for Privoxy)
# Expires: 12 hours
# Redirect: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt
# Lisens / Licence: https://github.com/DandelionSprout/adfilt/blob/master/LICENSE.md
# 🇳🇴: Denne listen dekker nettsteder for Norge, Danmark, Island, Færøyene, Grønland, og samebefolkningen. For mere informasjon, detaljer, hjelpemidler, og andre lister jeg har laget, gå til https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#norsk
# 🇩🇰: Denne liste dækker websider for Danmark, Norge, Island, Færøerne, Grønland, og den samiske befolkning. For mere information, detaljer, nyttige værktøjer og andre lister, jeg har lavet, besøg https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md
# Description: 🇬🇧: This list covers websites for Norway, Denmark, Iceland, Danish territories, and the Sami indigenous population. For more information, details, helpful tools, and other lists that I've made, visit https://github.com/DandelionSprout/adfilt/blob/master/Wiki/General-info.md#english
# If you wish to remove cookie banners from Nordic websites, check out https://www.i-dont-care-about-cookies.eu/
#
# 🇳🇴: Ukategoriserte oppføringer
# 🇩🇰: Ukategoriserede opføringer
{+block{Uncategorised entries}}
.oasfile
#
#
.viasport-assets.mtg-api.com/*/prod/comScore-*.js
.isweb.no
.opinion.peytz.dk
.tns-gallup.dk
.userneeds.dk
.gamereactor.*/lay/ad-video-stats.
.gamereactor.*/lay/js/adblock_desktop.
.gamereactor.*/lay/js/background.
.gamereactor.*/lay/js/banners_config.
.openx.gamereactor.dk/multi.php?
.viafree.*/collect
.gamereactor.*/media/eventad/
.cdn.ravenjs.com
.client-stream-events.mtg-api.com
.freewheel-mtgx-tv.akamaized.net
.getsentry.com
.sentry-cdn.com
.media.gamereactor.dk/prerolls/*
.ssl.p.jwpcdn.com*/freewheel.js
.ssl.p.jwpcdn.com*/gapro.js
.ssl.p.jwpcdn.com*/jwpsrv.js
.ssl.p.jwpcdn.com*/sharing.js
.ssl.p.jwpcdn.com*/vast.js
/_bm/abd
/insert_grtv_stats.
/prerolls/*
/adblock_mobile.
/linktag2.js
/viewability.
.avod-fw-config.mtg-api.com
.acdn.adnxs.com/ast/ast.js
.acdn.adnxs.com/ast/ast.js
.ssl.p.jwpcdn.com*/jwpsrv.js
.ssl.p.jwpcdn.com*/vast.js
.damoh.vgtv.no/hic_qos
/entag.js
.akamaihd.net/video-assets/
#
# Ads (Section under construction)
.ad.*.no
.ad1.*.no
.ad1.*.dk
.adcache.*.no
.ads.*.no
.ads.*.dk
.adserver.*.dk
.adservicemedia.dk
.annonser.*.no
.banner.*.no
.helios.*.no
.euroads.dk
.austevollforlag.no/wp-content/*/annonsar/
.austevollforlag.no/wp-content/*/yachtmarine2014.
.norskenettsider.no/images/remember-banner-2016.jpg
.norskenettsider.no/images/ageras-banner.jpg
.eyjar.net/skrar/ads
.amino.dk/images/partners/agera/240x140-forside-hardcoded*.jpg
.nvnytt.no/images/*annonse-
.track.adform.net
.track.adform.net/Banners/
.tvshop.com/tradedoubler_files/
.bornholm.nu/nonsec/banner
.delivered-by-madington.com
.media.sonymusic.no/marketing/*.html
.klikk.no/common/js/klikk.desktop-thirdparty.min.js
.dust2.dk/img/banners/*
.openadex.dk
.dotbanner.dk
.cluster.chart.dk
.vikari.is/skjol/frjalsi-lif*.png
.banner.landbrugsavisen.dk/reklame.aspx
.gratisxxx.no
.svonm.com/hd-main.js
.vevlysingar.fo
.boligkanalen-maestro-new.azurewebsites.net
/*-annonse-*
-bazaar-
/bazaar/*
.dk/ad/
.dk/ads/
.is/ad/
.is/ads/
.is/augl/
.is/skrar/augl/
.no/ad/
.no/ads/
/reklam/*
/reklame/*
/annonse/*
/auglysing/*
/bilder/erotikk1.jpg
/Bannere/*
.akamai.net
/js/smartbanner/*
/liveodds-button_nordicbet
/nordicbet_logo
/partners/*_ad_icon
#
# Leftover empty spaces that EasyList have left behind (Section under construction)
.gaysir.no/rek/bb_inline
# — — — — —
# https://sol.no/
# http://www.qxl.no/
# https://www.vtb.no/
# https://vafo.dk/
# https://reelligestilling.dk/
# https://www.rbnett.no/
# https://www.op.no/
# https://journalisten.dk/
# http://www.altomfotball.no/
#
{+block{Empty divider spaces (Section under construction)}}
#
{+block{Distracting background images (Section under construction)}}
.images.media.xxlsports.com/images/h90/h9d/9339713159198/bg.jpg
.platekompaniet.no/assets/img/background.png
.pepcall.no/wp-content/uploads/2015/04/bakgrunn-forside.jpg
#
{+block{Unbreakage}}
# 🇳🇴: Fikser videoavspillerene på nettstedene til norske fotballklubber når man bruker «uBlock Filters - Unbreak»
{+block{Fixes video players on Norwegian football club sites when using "uBlock Filters - Unbreak"}}
# 🇩🇰: Gør det muligt igen at scrolle når «I Don't Care About Cookies» er benyttet
{+block{Re-enables scrolling when using "I Don't Care About Cookies"}}
.scripts.tv2a.dk/oil/
{+block{Unbreaks significant content breakage when using "Fanboy's Social Blocking List", if I recall correctly}}
#
{+block{A(n incomplete) category for anti-anti-adblocking, in the event that https://forums.lanik.us/viewtopic.php?f=23&t=42273 were to specifically mention such entries as a reason to be denied EasyList affiliation or native ABP inclusion, in which case they'd be moved to the extension file}}
.elderlyscissors.com
.vg.no/cnp-assets/src/sites/vg/components/AdblockModal
#
#
#
# 🇳🇴: Multidomeneoppføringer
# 🇩🇰: Multidomæneposter
{+block{Multi-domain entries}}
#
#
#
#
#
# 🇳🇴: Norsk Tipping, inkl. tvilsomt motiverte lottoreklamer (Noen ikke-påtrengende tippereklamer er greit nok i mine øyne)
{+block{Norsk Tipping, incl. poorly motivated lotto ads (A few non-pushy football pool ads are fine in my book)}}
.widget.norsktippingpartner.no
.widget.tippebannere.no
.tipster.no/embed
#
# Fixing very severe misadvertising on Elkjøp and Elgiganten Denmark, in which the EU energy labels for a lot of products were still showing the colours of the pre-2016 labels, leading to cases where e.g. an A label was dark green while an A+ label was yellow with a hint of green.
# Amazingly, this does not seem to be a problem on elko.is or elding.fo, so kudos to them.
#
# Reducing the size of an extremely big Facebook link button
#
#
#
{+block{Category: Website-specific}}
#
# VG
.static.vg.no/css/admark_top.gif
.vglista.no/wp-content/themes/vglista/img/partner/
# ↓ Attempts to resolve how some frontpage articles are hard to open when using EasyPrivacy. ↓
#
# 🇳🇴: TV2
# 🇩🇰: TV2 Norge
{+block{TV2 Norway}}
.tv2.no/s/lab/2.5/p/img/tv2-background.svg
# ↓ Attempting to fix a problem with voting online on Idol Norway when using EasyPrivacy. ↓
#
# Nettavisen
# It was difficult to place the line between adticles that had educational values and which ones that didn't, but I feel I did a decent job at it
/resources/dfp/*
#
# Filmweb
.filmweb.no/template_v2/adverticement/
#
# ——————————————————————————————————————————————————————
#
{+block{Category: Entire domains, scams, and phishing}}
#
# 🇳🇴: Regler for hele nettsteder, som er kategorisert for å gjøre det enklere for meg å lage en «hosts»-versjon av denne listen
{+block{Rules for entire websites, categorised to make it easier for me to make a \"hosts\" version of this list}}
.ad.no.doubleclick.net
.webclick.no
.webhotell.enivest.no
.rig.idg.no
.adext.inkclub.com
.ads.no
.euroads.no
.primetime.ad.primetime.net
.myad.no
.nettklikk.no
.i1media.no
.easy-ad.no
.emerio.no
.cmt.no
.piwik.onlinemagasinet.no
.bannere.oslonett.no
#
# 🇳🇴: Solcellespesialisten, innlastingsproblem
{+block{Solcellespesialisten, loading issue}}
.wo.tc
#
# ——————————————————————————————————————————————————————————————
#
{+block{Category: Particularly appreciated fan contributions}}
#
# 🇳🇴: Lagt til etter forespørsel fra tilhengere og bidragsytere
# 🇩🇰: Tilføjet efter anmodninger fra tilhængere og bidragydere
{+block{Added on requests from fans and contributors}}
.sannsyn.com
# https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-493478718
#
# 🇳🇴: Nettsteder jeg nekter å besøke selv for å førstehåndsteste oppføringene
{+block{Sites that I refuse to visit on my own to test the entries}}
#
# 🇳🇴: Vindusviskere for betalte artikler (sånn at de nederste linjene i en forhåndsvisning ikke toner ut)
# Takk til THEtomaso (https://github.com/THEtomaso) for de fleste av disse oppføringene.
# 🇩🇰: Vinduesviskere for betalte artikler (så de sidste par linjer i en forhåndsvisning ikke falder ud)
# Tak til THEtomaso (https://github.com/THEtomaso) for de fleste av disse opføringer.
{+block{De-blurrers for paid articles (so that the last few lines of a preview doesn't fade out)}}
# Thanks to THEtomaso (https://github.com/THEtomaso) for most of these entries.
.dagligvarehandelen.no/sites/all/themes/custom/ledelseas/gfx/veil.png
#
# ——————————————————————————————————————————————————————————————————————————————————————————————————————
#
{+block{Category: Compatibility entries for ABP users, EasyList, and/or functionality whitelisting}}
#
# 🇳🇴: Nordensrelaterte oppføringer som har blitt foreslått for store internasjonale lister, men som ikke har blitt lagt til dem som det er meg bekjent
# 🇩🇰: Nordenrelaterede poster, der er blevet foreslået til store internationale lister, men som ikke er blevet tilføjet til dem endnu som det er meg bekendt
{+block{Nordics-related entries that have been suggested to major international lists, but which haven't been added to them yet or for long}}
# https://github.com/easylist/easylist/issues/1861
#
# 🇳🇴: Hvitelisting av sporere som er nødvendige for brukere av Prisjakt, Kickback, og Viatrumf
# 🇩🇰: Tracker-hvidlistninger, der er nødvendige for brugere af Prisjakt, Kickback og Viatrumf (Norske handletjenester)
{+block{Tracker whitelistings that are necessary for users of Prisjakt, Kickback, and Viatrumf}}
# 🇳🇴: Lagt til fordi min egen mor (Hun er i 40-årene) trodde jeg hadde rotet til PCen hennes, når den i stedet bare viste en uBO-sideadvarsel på grunn av en oppføring i «AdGuards hovedfilter», også kjent som AdGuard Base.
{+block{Added because my own mom (She's in her 40s) thought I had messed up her PC, when instead it just displayed a uBO page warning due to an AdGuard Base entry.}}
#
# 🇳🇴: Landseksklusive versjoner for enkle reklameblokkerere, av flernasjonsoppføringer som er i utvidelsesfilen for avanserte reklameblokkerere; ettersom Adblock Plus og AdGuard for øyeblikket ikke støtter *-jokertegn i nettadressene til blokkeringsregler.
# ABP diskuterte på et tidspunkt å støtte det i https://issues.adblockplus.org/ticket/6773, men det bunnet ut i ingenting.
# 🇩🇰: Landseksklusive versioner til enkle adblockere, af flerlandsposter, der findes i udvidelsesfilen for avancerede adblockere; eftersom Adblock Plus og AdGuard i øjeblikket ikke understøtter * -jokertegn i blokeringsregel-URL-er.
# ABP drøftede på et tidspunkt at støtte det i https://issues.adblockplus.org/ticket/6773, men det førede ikke til noget.
{+block{Country-exclusive versions for simple adblockers, of multi-country entries that are found in the extensions file for advanced adblockers; because Adblock Plus and AdGuard currently doesn't support *-wildcards in blocking-rule URLs.}}
# ABP was at one point discussing supporting it in https://issues.adblockplus.org/ticket/6773, but it stranded out into nothing.
#
.openx.gamereactor.dk/multi.php?
#
#
#
{+block{Entries that are also present in AdGuard English Filter, for those who use ABP and AdBlock, or who haven't felt a need to spend 8 seconds to subscribe to it in uBlock Origin.}}
#
#
#
#
#
# JavaScript features baked into Nano Adblocker and uBlock Origin
#
#
#
# Wildcard versions of various entries. Because why only block on one national version of a site, when you can nowadays block on all versions of a site without cluttering things up?
#
#
# ——————————————————————————————————————————————————————————————————————————————————————————
#
# 🇳🇴: Svindelnettsteder og virusnettsteder (Ikke besøk dem hvis du har dine datamaskiner og lommebøker kjært)
# Rask leksjon: Mange svindelnettsteder bruker adresser som ligner på adressene til store nettsteder, men som inneholder tilfeldige ekstra smådetaljer som gjør dem til en helt annen adresse. ".vg.no." vil blokkere vg.no.iphone-svindel-eksempel.xyz, men ikke vg.no eller vg.no/sport
# 🇩🇰: Fupsider og virussider (Besøg dem ikke, hvis du sætter pris på dine computere og tegnebøger)
{+block{Scam sites and virus sites (Do not visit them if you value your computers and wallets)}}
# Quick 101: Many scam sites use addresses that resemble those of major sites, but which contain random extra tidbits that make them a whole different address. ".vg.no." will block vg.no.iphone-scam-example.xyz, but not vg.no or vg.no/sport
.kjolenorge.com
.paypal.*.no
.vg.no.
.elkjop.no.
.coop.no.
.shell.no.
.finn.no.
.posten.no.
.postnord.no.
.*/finn.no/finno.htm
.dnb.no.
.sparebank1.no.
.nordea.no.
.sbanken.no.
.danskebank.no.
.*/?finn.no/login
.komplett.no.
.nordnet.no.
.skatteetaten.no.
.*/begrensede-tilbudet/
.norwegian.com.
.flysas-no.
.tusenfryd-com.
.*/bli-avbrutt-bor-du-oppdater/
.*/Norgesecure/
..gratis-reisebilletter.
.*/KiwiErbjudanden1/
.trackvoluum.com
.testgruppens.com
.jagerjack.com
.*/pakkerlevering/
.posten.club
.kundklubb-se.com
.norwayexpress24.com
.prisjakt.org
.postnord-norge.com
.streetdance.no
.102.112.2o7.net
.vetscan.no
.tromselementbygg.no
.brannloftet.no
.butikk.losnaspelet.no
.no.zxxyw.com
.oyelege.no
.fanadyreklinikk.no
.digitoday.com
.komtilmil.no
.apple-account-locked.losjevegen.no
.arendalfotball.no
.arvetellefsen.no/curry
.handelihalden.no
.holmedalblikk.no
#
# 🇳🇴: Som nevnt i https://www.dagbladet.no/kultur/jeg-blir-hver-dag-kontaktet-av-folk-som-faktisk-tror-pa-denne-svindelen/70487841
{+block{As mentioned in https://www.dagbladet.no/kultur/jeg-blir-hver-dag-kontaktet-av-folk-som-faktisk-tror-pa-denne-svindelen/70487841}}
.breakoutstory24.com
.thefivereport.online
.abafort.us
#
# 🇳🇴: Som nevnt i https://www.tv2.no/nyheter/10493336/
.rnbinance.com
.brightertrade.com
#
# Som nevnt i https://www.nrk.no/ytring/1.14496024
.cost2buy.net
#
# Som nevnt i https://www.nrk.no/norge/1.14511067
.kongeparken.com-*
.com-fryd.com
.kiwi.com-*
.com-norwegian.com
#
# Som nevnt i https://www.aftenposten.no/osloby/i/mRK8xq/Fatt-tilbud-om-gratis-kollektivbillett-Svindel_-melder-Ruter
.ruter.top
#
# Som nevnt i https://www.faktisk.no/faktasjekker/YAb/nei-olav-thon-har-ikke-investert-850-millioner-kroner-i-bitcoin-program
.101mesh.com
.gokkw.com
.earnmoneyglobal.com
#
# Som nevnt i https://www.datahjelperne.no/stein-erik-hagen-og-fredrik-skavlan-misbrukes-i-bitcoin-svindel/
.trendyn.me
#
# Som nevnt i https://www.datahjelperne.no/verifiser-get-konto-falsk-mail/
.getmail-no.*
#
# Som nevnt i https://www.datahjelperne.no/falske-telenor-undersokelser/
.surveryrewards1.com
#
# Som nevnt i https://www.nrk.no/mr/1.14649436
.pprfct.com
#
# 🇳🇴: Falske nett-"butikker" som er så dårlige, at de står oppført på Forbrukertilsynet egen svarteliste.
# 🇩🇰: Falske web-"butikker" der er så dårlige, at de er opført på svartelisten til Forbrukertilsynet (Norges svar på Forbrugerombudsmanden).
{+block{Fake and fraudulent web-"stores" that are so bad, that they're listed on the blacklist of the Norwegian state-sponsored Consumer Authority.}}
# Source: https://www.forbrukertilsynet.no/netthandel/falske-nettbutikker.
.adamaruiz.org
.adidasko.com
.adidassuperstarnorge.com
.airmaxskobillige.com
.allergyfl.com
.apcleverstore.com
.apvoc-ga.com
.ashskonorge.com
.assassinfitness.com
.beblessedbehappy.org
.benshermanoslo.com
.billigesalg.com
.billigskos.com
.bilstokken.com
.bncentertainment.com
.bostongrnhsflowers.com
.caperforaciones.com
.charpente-ramel.com
.coralls.com
.crossfiterada.com
.crownedwithlaurels.com
.daradis.com
.denningwelldrilling.com
.drakternorge.com
.drcarolyngroff.com
.dunjakke-no.com
.easyliving4you.com
.eurosko.net
.fatalfailblog.com
.festmusikk.com
.fotballsko-salg.com
.fotballskotilbud.com
.gantoslo.com
.godeskonettbutikk.com
.godsfillingstation.org
.gsport.com
.helseprodukt.co
.hernoclothing.com
.hollisternorge.com
.horizonbagel.com
.itsthetrendydealstore.com
.imprimtacom.com
.jakker.co
.jakkesalgs.com
.jakkesnorge.com
.joseph-holland.com
.klmyu.com
.jessicaivory.com
.legarralazcoz.com
.lillevinkelsko.net
.lindseysopticians.com
.linkshe.com
.locchalet2alpes.com
.lrgst.com
.lymaq.com
.manasporthorse.com
.mayor4london.com
.mbtnorge.com
.meadtalkofthetown.com
.meladermfacts.com
.mncprobuild.com
.moebel-thiems.com
.moslt.com
.moteshoes.com
.mrarmstrongsclass.com
.mudancaslvc.com
.museuw.com
.mycraftypad.com
.nasajones.com
.nikebutikks.com
.no.moncleritalien.com
.nordartisan.com
.norfotball.com
.norgefotball.com
.norge.parkaoutdoor.com
.norgejakke.com
.norgejakkerbutikk.com
.norgeshoes.com
.nyeskonorge2015.com
.nywlm.com
.oflike.com
.omgrm.com
.ontariokitcarbuilders.com
.parajumpers-longbear.com
.parajumpers-salg.com
.parajumpersitoutlet.com
.parajumpersit.com
.parajumperjakke.net
.parajumpersnettbutikk.com
.parajumpers-norge.site
.parajumpersnorway.com
.parajumperssalg.com
.parajumpersoutletnorge.com
.pmnft.com
.pjs.outlet.com
.popeurope.com
.quiltstudiolaren.com
.reeconindustries.com
.retoaudi.com
.scottfamilyministries.org
.skoeccosandaler.com
.skonmdnorge.com
.sykkeltrøye.com
.ssrodeolivestock.com
.swellsup.com
.tiranaaquapark-eg.com
.tobiascelebritymusicevents.com
.um-bs.com
.vansnorge.com
.wausauorthopedics.com
.zaskal.com
#
{+block{Pirate-product-selling stores registered by the serial scammers who go by the name of "xiang dao xin xi ji shu you xiang gong si".}}
.nofotballshop.com
.nofotballstore.com
.dkfodboldstore.com
